/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _CAM_IFE_CSID_1080_H_
#define _CAM_IFE_CSID_1080_H_

#include <linux/module.h>
#include "cam_ife_csid_dev.h"
#include "camera_main.h"
#include "cam_ife_csid_common.h"
#include "cam_ife_csid_hw_ver2.h"
#include "cam_irq_controller.h"
#include "cam_isp_hw_mgr_intf.h"

#define CAM_CSID_VERSION_V1080                 0x100080000

static const struct cam_ife_csid_irq_desc cam_ife_csid_1080_rx_irq_desc[][32] = {
	{
		{
			.bitmask = BIT(0),
			.desc = "DL0_EOT",
		},
		{
			.bitmask = BIT(1),
			.desc = "DL1_EOT",
		},
		{
			.bitmask = BIT(2),
			.desc = "DL2_EOT",
		},
		{
			.bitmask = BIT(3),
			.desc = "DL3_EOT",
		},
		{
			.bitmask = BIT(4),
			.desc = "DL0_SOT",
		},
		{
			.bitmask = BIT(5),
			.desc = "DL1_SOT",
		},
		{
			.bitmask = BIT(6),
			.desc = "DL2_SOT",
		},
		{
			.bitmask = BIT(7),
			.desc = "DL3_SOT",
		},
		{
			.bitmask = BIT(8),
			.desc = "DPHY_PH_ECC_SEC",
		},
		{
			.bitmask = BIT(9),
			.desc = "SENSOR_MODE_ID_CHANGE",
		},
		{0},
		{0},
		{
			.bitmask = BIT(12),
			.desc =
				"DL0_EOT_LOST, Sensor: Issue is with the timing signals received in the cphy packet on lane 0 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(13),
			.desc =
				"DL1_EOT_LOST, Sensor: Issue is with the timing signals received in the cphy packet on lane 1 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(14),
			.desc =
				"DL2_EOT_LOST, Sensor: Issue is with the timing signals received in the cphy packet on lane 2 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(15),
			.desc =
				"DL3_EOT_LOST, Sensor: Issue is with the timing signals received in the cphy packet on lane 3 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(16),
			.desc =
				"DL0_SOT_LOST, Sensor: Timing signals are missed received in the cphy packet on lane 0 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(17),
			.desc =
				"DL1_SOT_LOST, Sensor: Timing signals are missed received in the cphy packet on lane 1 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(18),
			.desc =
				"DL2_SOT_LOST, Sensor: Timing signals are missed received in the cphy packet on lane 2 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(19),
			.desc =
				"DL3_SOT_LOST, Sensor: Timing signals are missed received in the cphy packet on lane 3 - Check phy/sensor config",
		},
		{
			.bitmask = BIT(20),
			.desc =
				"DL0_FIFO_OVERFLOW, System: Data has been lost when transferring from PHY to CSID on Lane 0 - Check PHY clock, CSID clock and possible skew among the data lanes",
		},
		{
			.bitmask = BIT(21),
			.desc =
				"DL1_FIFO_OVERFLOW, System: Data has been lost when transferring from PHY to CSID on Lane 1 - Check PHY clock, CSID clock and possible skew among the data lanes",
		},
		{
			.bitmask = BIT(22),
			.desc =
				"DL2_FIFO_OVERFLOW, System: Data has been lost when transferring from PHY to CSID on Lane 2 - Check PHY clock, CSID clock and possible skew among the data lanes",
		},
		{
			.bitmask = BIT(23),
			.desc =
				"DL3_FIFO_OVERFLOW, System: Data has been lost when transferring from PHY to CSID on Lane 3 - Check PHY clock, CSID clock and possible skew among the data lanes",
		},
		{
			.bitmask = BIT(24),
			.desc =
				"CPHY_PH_CRC, Sensor: All CPHY packet headers received are corrupted - Check phy/sensor config",
		},
		{
			.bitmask = BIT(25),
			.desc =
				"PAYLOAD_CRC, Sensor: The calculated CRC of a long packet does not match the transmitted (expected) CRC, possible corruption - Check phy/sensor config",
		},
		{
			.bitmask = BIT(26),
			.desc =
				"DPHY_PH_ECC_DED, Sensor: A short or long packet is corrupted and cannot be recovered - Check phy/sensor config",
		},
		{
			.bitmask = BIT(27),
			.desc =
				"MMAPPED_VC_DT, SW: A long packet has a VC_DT combination that is configured for more than one IPP or RDIs",
		},
		{
			.bitmask = BIT(28),
			.desc =
				"UNMAPPED_VC_DT, Sensor: A long packet has a VC_DT combination that is not configured for IPP or RDIs",
		},
		{
			.bitmask = BIT(29),
			.desc =
				"STREAM_UNDERFLOW, Sensor: Long packet payload size is less than payload header size, resulting a corrupted frame - Perform PHY Tuning/Check sensor limitations",
		},
		{0},
		{
			.bitmask = BIT(31),
			.desc = "CSI2_RX_IRQ_STATUS_2",
		},
	},
	{
		{
			.bitmask = BIT(0),
			.desc =
				"LONG_PKT, Debug: The header of the first long pkt matching the configured vc-dt has been captured",
		},
		{
			.bitmask = BIT(1),
			.desc =
				"SHORT_PKT, Debug: The header of the first short pkt matching the configured vc-dt has been captured",
		},
		{
			.bitmask = BIT(2),
			.desc =
				"CPHY_PKT_HDR, Debug: The header of the first cphy pkt matching the configured vc-dt has been captured",
		},
		{
			.bitmask = BIT(3),
			.desc = "Illegal programming for next frame ID config",
		},
	},
};

static const uint32_t cam_ife_csid_1080_num_rx_irq_desc[] = {
	ARRAY_SIZE(cam_ife_csid_1080_rx_irq_desc[0]),
	ARRAY_SIZE(cam_ife_csid_1080_rx_irq_desc[1]),
};

static const struct cam_ife_csid_irq_desc cam_ife_csid_1080_path_irq_desc[] = {
	{
		.bitmask = BIT(0),
		.err_type = CAM_ISP_HW_ERROR_CSID_FATAL,
		.irq_name = "ILLEGAL_PROGRAMMING",
		.desc = "SW: Illegal programming sequence",
		.debug = "Check the following possiblities:",
		.err_handler = cam_ife_csid_ver2_print_illegal_programming_irq_status,
	},
	{0},
	{
		.bitmask = BIT(2),
		.irq_name = "INFO_DATA_FIFO_FULL",
	},
	{
		.bitmask = BIT(3),
		.irq_name = "CAMIF_EOF",
	},
	{
		.bitmask = BIT(4),
		.irq_name = "CAMIF_SOF",
	},
	{0},
	{0},
	{
		.bitmask = BIT(7),
		.err_type = CAM_ISP_HW_ERROR_CSID_ILLEGAL_DT_SWITCH,
		.irq_name = "ILLEGAL_DT_SWITCH",
		.desc = "SW: Change in DT without MUP",
		.debug = "Check sensor configuration",
		.err_handler = cam_ife_csid_hw_ver2_mup_mismatch_handler,
	},
	{0},
	{
		.bitmask = BIT(9),
		.irq_name = "INFO_INPUT_EOF",
	},
	{
		.bitmask = BIT(10),
		.irq_name = "INFO_INPUT_EOL",
	},
	{
		.bitmask = BIT(11),
		.irq_name = "INFO_INPUT_SOL",
	},
	{
		.bitmask = BIT(12),
		.irq_name = "INFO_INPUT_SOF",
	},
	{
		.bitmask = BIT(13),
		.err_type = CAM_ISP_HW_ERROR_CSID_FRAME_SIZE,
		.irq_name = "ERROR_PIX_COUNT",
		.desc = "SW: Mismatch in expected versus received number of pixels per line",
		.debug = "Check SW config/sensor stream",
		.err_handler = cam_ife_csid_ver2_print_format_measure_info,
	},
	{
		.bitmask = BIT(14),
		.err_type = CAM_ISP_HW_ERROR_CSID_FRAME_SIZE,
		.irq_name = "ERROR_LINE_COUNT",
		.desc = "SW: Mismatch in expected versus received number of lines",
		.debug = "Check SW config/sensor stream",
		.err_handler = cam_ife_csid_ver2_print_format_measure_info,
	},
	{
		.bitmask = BIT(15),
		.irq_name = "VCDT_GRP1_SEL",
	},
	{
		.bitmask = BIT(16),
		.irq_name = "VCDT_GRP0_SEL",
	},
	{
		.bitmask = BIT(17),
		.irq_name = "VCDT_GRP_CHANGE",
	},
	{
		.bitmask = BIT(18),
		.err_type = CAM_ISP_HW_ERROR_CSID_CAMIF_FRAME_DROP,
		.irq_name = "CAMIF_FRAME_DROP",
		.desc =
			"Sensor: The pre CAMIF frame drop would drop a frame in case the new frame starts prior to the end of the previous frame",
		.debug = "Slower downstream processing or faster frame generation from sensor",
	},
	{
		.bitmask = BIT(19),
		.err_type = CAM_ISP_HW_ERROR_RECOVERY_OVERFLOW,
		.irq_name = "OVERFLOW_RECOVERY",
		.desc = "Detected by the overflow recovery block",
		.debug = "Backpressure downstream",
	},
	{
		.bitmask = BIT(20),
		.irq_name = "ERROR_REC_CCIF_VIOLATION",
		.desc = "Output CCIF has a violation with respect to frame timing",
	},
	{
		.bitmask = BIT(21),
		.irq_name = "CAMIF_EPOCH0",
	},
	{
		.bitmask = BIT(22),
		.irq_name = "CAMIF_EPOCH1",
	},
	{
		.bitmask = BIT(23),
		.irq_name = "RUP_DONE",
	},
	{
		.bitmask = BIT(24),
		.irq_name = "ILLEGAL_BATCH_ID",
		.desc = "SW: Decoded frame ID does not match with any of the programmed batch IDs",
		.debug = "Check frame ID and all available batch IDs",
	},
	{
		.bitmask = BIT(25),
		.irq_name = "BATCH_END_MISSING_VIOLATION",
		.desc = "SW: Input number of frames is not a multiple of the batch size",
		.debug = "Check the configured pattern/period for batching",
	},
	{
		.bitmask = BIT(26),
		.irq_name = "UNBOUNDED_FRAME",
		.desc = "Sensor: Frame end or frame start is missing",
		.debug = "Check the settle count in sensor driver XML",
	},
	{
		.bitmask = BIT(27),
		.irq_name = "ERROR_SER_INVALID_CTXT",
		.desc = "Indicates invalid context on CCIF",

	},
	{
		.bitmask = BIT(28),
		.irq_name = "SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP",
		.desc =
			"Sensor/SW: The programmed MUP is out of sync with the VC of the incoming frame",
		.err_handler = cam_ife_csid_hw_ver2_mup_mismatch_handler,
	},
	{
		.bitmask = BIT(29),
		.irq_name = "CCIF_VIOLATION",
		.desc =
			"The output CCIF from the serializer has a violation with respect to frame timing",
	},
};

static const struct cam_ife_csid_top_irq_desc cam_ife_csid_1080_top_irq_desc[][32] = {
	{
		{
			.bitmask  = BIT(1),
			.err_type = CAM_ISP_HW_ERROR_CSID_SENSOR_SWITCH_ERROR,
			.err_name = "FATAL_SENSOR_SWITCHING_IRQ",
			.desc =
				"Sensor/SW: Minimum VBI period between dynamically switching between two sensor modes was either violated or the downstream pipe was not active when the switch was made",
		},
	},
	{
		{
			.bitmask  = BIT(2),
			.err_name = "ERROR_NO_VOTE_DN",
			.desc =
				"DRV: vote_down is never generated for the same frame and resource is never relinquished",
			.debug = "Check vote up generated time",
		},
		{
			.bitmask  = BIT(3),
			.err_type = CAM_ISP_HW_ERROR_RECOVERY_OVERFLOW,
			.err_name = "ERROR_VOTE_UP_LATE",
			.desc = "DRV: vote_up is generated after SOF",
			.debug = "Check the vote up timer value",
			.err_handler = cam_ife_csid_hw_ver2_drv_err_handler,
		},
		{
			.bitmask  = BIT(4),
			.err_type = CAM_ISP_HW_ERROR_CSID_OUTPUT_FIFO_OVERFLOW,
			.err_name = "ERROR_RDI_LINE_BUFFER_CONFLICT",
			.desc =
				"System/SW: Multiple RDIs configured to access the same shared line buffer, more of a SW issue that led to this programming",
			.err_handler = cam_ife_csid_hw_ver2_rdi_line_buffer_conflict_handler,
		},
		{
			.bitmask = BIT(5),
			.err_name = "ERROR_SENSOR_HBI",
			.desc = "Sensor: Sensor HBI is less than expected HBI",
			.debug = "Check sensor configuration",
		},
	},
};

static const uint32_t cam_ife_csid_1080_num_top_irq_desc[] = {
	ARRAY_SIZE(cam_ife_csid_1080_top_irq_desc[0]),
	ARRAY_SIZE(cam_ife_csid_1080_top_irq_desc[1]),
};

static const char *cam_ife_csid_1080_debug_vec_desc[][32] = {
	{
		"ERROR_UNBOUNDED_FRAME_RDI1",
		"ERROR_SER_INVALID_CTXT_RDI1",
		"ERROR_SER_CCIF_VIOLATION_RDI1",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_RDI1",
		"ERROR_REC_FRAME_DROP_RDI1",
		"ERROR_REC_OVERFLOW_RDI0",
		"ERROR_CAMIF_CCIF_VIOLATION_RDI0",
		"ERROR_ILLEGAL_BATCH_ID_RDI0",
		"ERROR_UNBOUNDED_FRAME_RDI0",
		"ERROR_SER_INVALID_CTXT_RDI0",
		"ERROR_SER_CCIF_VIOLATION_RDI0",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_RDI0",
		"ERROR_REC_FRAME_DROP_RDI0",
		"ERROR_REC_OVERFLOW_PPP",
		"ERROR_CAMIF_CCIF_VIOLATION_PPP",
		"ERROR_ILLEGAL_BATCH_ID_PPP",
		"ERROR_UNBOUNDED_FRAME_PPP",
		"ERROR_SER_INVALID_CTXT_PPP",
		"ERROR_SER_CCIF_VIOLATION_PPP",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_PPP",
		"ERROR_REC_FRAME_DROP_PPP",
		"ERROR_DL0_FIFO_OVERFLOW",
		"ERROR_DL1_FIFO_OVERFLOW",
		"ERROR_DL2_FIFO_OVERFLOW",
		"ERROR_DL3_FIFO_OVERFLOW",
		"ERROR_CPHY_PH_CRC",
		"ERROR_DPHY_PH_ECC_DED",
		"ERROR_STREAM_UNDERFLOW",
		"ERROR_NO_VOTE_DN",
		"ERROR_VOTE_UP_LATE",
		"ERROR_RDI_LINE_BUFFER_CONFLICT",
		"ERROR_SENSOR_HBI"
	},
	{
		"ERROR_UNBOUNDED_FRAME_IPP0",
		"ERROR_SER_INVALID_CTXT_IPP0",
		"ERROR_SER_CCIF_VIOLATION_IPP0",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_IPP0",
		"ERROR_REC_FRAME_DROP_IPP0",
		"ERROR_REC_OVERFLOW_RDI4",
		"ERROR_CAMIF_CCIF_VIOLATION_RDI4",
		"ERROR_ILLEGAL_BATCH_ID_RDI4",
		"ERROR_UNBOUNDED_FRAME_RDI4",
		"ERROR_SER_INVALID_CTXT_RDI4",
		"ERROR_SER_CCIF_VIOLATION_RDI4",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_RDI4",
		"ERROR_REC_FRAME_DROP_RDI4",
		"ERROR_REC_OVERFLOW_RDI3",
		"ERROR_CAMIF_CCIF_VIOLATION_RDI3",
		"ERROR_ILLEGAL_BATCH_ID_RDI3",
		"ERROR_UNBOUNDED_FRAME_RDI3",
		"ERROR_SER_INVALID_CTXT_RDI3",
		"ERROR_SER_CCIF_VIOLATION_RDI3",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_RDI3",
		"ERROR_REC_FRAME_DROP_RDI3",
		"ERROR_REC_OVERFLOW_RDI2",
		"ERROR_CAMIF_CCIF_VIOLATION_RDI2",
		"ERROR_ILLEGAL_BATCH_ID_RDI2",
		"ERROR_UNBOUNDED_FRAME_RDI2",
		"ERROR_SER_INVALID_CTXT_RDI2",
		"ERROR_SER_CCIF_VIOLATION_RDI2",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_RDI2",
		"ERROR_REC_FRAME_DROP_RDI2",
		"ERROR_REC_OVERFLOW_RDI1",
		"ERROR_CAMIF_CCIF_VIOLATION_RDI1",
		"ERROR_ILLEGAL_BATCH_ID_RDI1"
	},
	{
		"ERROR_REC_OVERFLOW_IPP0",
		"ERROR_CAMIF_CCIF_VIOLATION_IPP0",
		"ERROR_ILLEGAL_BATCH_ID_IPP0",
		"ERROR_REC_OVERFLOW_IPP2",
		"ERROR_CAMIF_CCIF_VIOLATION_IPP2",
		"ERROR_ILLEGAL_BATCH_ID_IPP2",
		"ERROR_UNBOUNDED_FRAME_IPP2",
		"ERROR_SER_INVALID_CTXT_IPP2",
		"ERROR_SER_CCIF_VIOLATION_IPP2",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_IPP2",
		"ERROR_REC_FRAME_DROP_IPP2",
		"ERROR_REC_OVERFLOW_IPP1",
		"ERROR_CAMIF_CCIF_VIOLATION_IPP1",
		"ERROR_ILLEGAL_BATCH_ID_IPP1",
		"ERROR_UNBOUNDED_FRAME_IPP1",
		"ERROR_SER_INVALID_CTXT_IPP1",
		"ERROR_SER_CCIF_VIOLATION_IPP1",
		"FATAL_SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP_IPP1",
		"ERROR_REC_FRAME_DROP_IPP1"
	}
};

static struct cam_irq_register_set cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_MAX] = {
	/* Top_1 */
	{
		.mask_reg_offset   = 0x00000184,
		.clear_reg_offset  = 0x00000188,
		.status_reg_offset = 0x00000180,
		.set_reg_offset    = 0x0000018C,
		.test_set_val      = BIT(0),
		.test_sub_val      = BIT(0),
		.force_rd_mask     = BIT(31), /* force read due to hw errata */
	},
	/* RX_1 */
	{
		.mask_reg_offset   = 0x000001B4,
		.clear_reg_offset  = 0x000001B8,
		.status_reg_offset = 0x000001B0,
	},
	/* RDI0 */
	{
		.mask_reg_offset   = 0x00000228,
		.clear_reg_offset  = 0x0000022C,
		.status_reg_offset = 0x00000224,
	},
	/* RDI1 */
	{
		.mask_reg_offset   = 0x00000238,
		.clear_reg_offset  = 0x0000023C,
		.status_reg_offset = 0x00000234,
	},
	/* RDI2 */
	{
		.mask_reg_offset   = 0x00000248,
		.clear_reg_offset  = 0x0000024C,
		.status_reg_offset = 0x00000244,
	},
	/* RDI3 */
	{
		.mask_reg_offset   = 0x00000258,
		.clear_reg_offset  = 0x0000025C,
		.status_reg_offset = 0x00000254,
	},
	/* RDI4 */
	{
		.mask_reg_offset   = 0x00000268,
		.clear_reg_offset  = 0x0000026C,
		.status_reg_offset = 0x00000264,
	},
	/* IPP_0 */
	{
		.mask_reg_offset   = 0x000001E8,
		.clear_reg_offset  = 0x000001EC,
		.status_reg_offset = 0x000001E4,
	},
	/* PPP */
	{
		.mask_reg_offset   = 0x000001D4,
		.clear_reg_offset  = 0x000001D8,
		.status_reg_offset = 0x000001D0,
	},
	/* UDI_0 */
	{0},
	/* UDI_1 */
	{0},
	/* UDI_2 */
	{0},

	/* Top_2 */
	{
		.mask_reg_offset   = 0x00000194,
		.clear_reg_offset  = 0x00000198,
		.status_reg_offset = 0x00000190,
		.set_reg_offset    = 0x0000019C,
	},
	/* RX_2 */
	{
		.mask_reg_offset   = 0x000001C4,
		.clear_reg_offset  = 0x000001C8,
		.status_reg_offset = 0x000001C0,
	},
	/* IPP_1 */
	{
		.mask_reg_offset   = 0x000001F8,
		.clear_reg_offset  = 0x000001FC,
		.status_reg_offset = 0x000001F4,
	},
	/* IPP_2 */
	{
		.mask_reg_offset   = 0x00000208,
		.clear_reg_offset  = 0x0000020C,
		.status_reg_offset = 0x00000204,
	},
};

static struct cam_irq_controller_reg_info cam_ife_csid_1080_top_irq_reg_info[] = {
	{
	.num_registers = 1,
	.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_TOP],
	.global_irq_cmd_offset = 0x00000110,
	.global_clear_bitmask  = 0x00000001,
	.global_set_bitmask    = 0x00000010,
	.clear_all_bitmask     = 0xFFFFFFFF,
	},
	{
	.num_registers = 1,
	.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_TOP_2],
	.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},

};

static struct cam_irq_controller_reg_info cam_ife_csid_1080_rx_irq_reg_info[] = {
	{
	.num_registers = 1,
	.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RX],
	.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
	.num_registers = 1,
	.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RX_2],
	.global_irq_cmd_offset = 0, /* intentionally set to zero */

	},
};

static struct cam_irq_controller_reg_info
	cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_MAX] = {
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_0],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_1],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_2],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_3],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_4],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_IPP],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_PPP],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	/* UDI_0 */
	{0},
	/* UDI_1 */
	{0},
	/* UDI_2 */
	{0},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_IPP_1],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_1080_irq_reg_set[CAM_IFE_CSID_IRQ_REG_IPP_2],
		.global_irq_cmd_offset = 0, /* intentionally set to zero */
	},

};

static struct cam_irq_register_set cam_ife_csid_1080_buf_done_irq_reg_set[1] = {
	{
		.mask_reg_offset   = 0x000001A4,
		.clear_reg_offset  = 0x000001A8,
		.status_reg_offset = 0x000001A0,
	},
};

static struct cam_irq_controller_reg_info
	cam_ife_csid_1080_buf_done_irq_reg_info = {
	.num_registers = 1,
	.irq_reg_set = cam_ife_csid_1080_buf_done_irq_reg_set,
	.global_irq_cmd_offset  = 0, /* intentionally set to zero */
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_ipp_reg_info = {
		.irq_status_addr                  = 0x01E4,
		.irq_mask_addr                    = 0x01E8,
		.irq_clear_addr                   = 0x01EC,
		.irq_set_addr                     = 0x01F0,
		.cfg0_addr                        = 0x0C80,
		.ctrl_addr                        = 0x0C88,
		.debug_clr_cmd_addr               = 0x0C8C,
		.multi_vcdt_cfg0_addr             = 0x0C90,
		.multi_vcdt_cfg1_addr             = 0x0C84,
		.cfg1_addr                        = 0,
		.sparse_pd_extractor_cfg_addr     = 0,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.bin_pd_detect_cfg0_addr          = 0,
		.bin_pd_detect_cfg1_addr          = 0,
		.bin_pd_detect_cfg2_addr	  = 0,
		.camif_frame_cfg_addr             = 0x0C94,
		.epoch_irq_cfg_addr               = 0,
		.epoch0_subsample_ptrn_addr       = 0,
		.epoch1_subsample_ptrn_addr       = 0,
		.debug_rup_aup_status             = 0x0C98,
		.debug_camif_1_addr               = 0x0C9C,
		.debug_camif_0_addr               = 0x0CA0,
		.frm_drop_pattern_addr            = 0x0CB8,
		.frm_drop_period_addr             = 0x0CBC,
		.irq_subsample_pattern_addr       = 0x0CC0,
		.irq_subsample_period_addr        = 0x0CC4,
		.hcrop_addr                       = 0,
		.vcrop_addr                       = 0,
		.pix_drop_pattern_addr            = 0,
		.pix_drop_period_addr             = 0,
		.line_drop_pattern_addr           = 0,
		.line_drop_period_addr            = 0,
		.debug_halt_status_addr           = 0x0CA4,
		.debug_misr_val0_addr             = 0x0CA8,
		.debug_misr_val1_addr             = 0x0CAC,
		.debug_misr_val2_addr             = 0x0CB0,
		.debug_misr_val3_addr             = 0x0CB4,
		.format_measure_cfg0_addr         = 0x0CC8,
		.format_measure_cfg1_addr         = 0x0CCC,
		.format_measure_cfg2_addr         = 0x0CD0,
		.format_measure0_addr             = 0x0CD4,
		.format_measure1_addr             = 0x0CD8,
		.format_measure2_addr             = 0x0CDC,
		.timestamp_curr0_sof_addr         = 0x0CE0,
		.timestamp_curr1_sof_addr         = 0x0CE4,
		.timestamp_perv0_sof_addr         = 0x0CE8,
		.timestamp_perv1_sof_addr         = 0x0CEC,
		.timestamp_curr0_eof_addr         = 0x0CF0,
		.timestamp_curr1_eof_addr         = 0x0CF4,
		.timestamp_perv0_eof_addr         = 0x0CF8,
		.timestamp_perv1_eof_addr         = 0x0CFC,
		.lut_bank_cfg_addr                = 0,
		.batch_id_cfg0_addr               = 0x0D00,
		.batch_id_cfg1_addr               = 0x0D04,
		.batch_period_cfg_addr            = 0x0D08,
		.batch_stream_id_cfg_addr         = 0x0D0C,
		.epoch0_cfg_batch_id0_addr        = 0x0D10,
		.epoch1_cfg_batch_id0_addr        = 0x0D14,
		.epoch0_cfg_batch_id1_addr        = 0x0D18,
		.epoch1_cfg_batch_id1_addr        = 0x0D1C,
		.epoch0_cfg_batch_id2_addr        = 0x0D20,
		.epoch1_cfg_batch_id2_addr        = 0x0D24,
		.epoch0_cfg_batch_id3_addr        = 0x0D28,
		.epoch1_cfg_batch_id3_addr        = 0x0D2C,
		.epoch0_cfg_batch_id4_addr        = 0x0D30,
		.epoch1_cfg_batch_id4_addr        = 0x0D34,
		.epoch0_cfg_batch_id5_addr        = 0x0D38,
		.epoch1_cfg_batch_id5_addr        = 0x0D3C,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x0D40,
		.path_frame_id                    = 0x0D44,

		/* configurations */
		.resume_frame_boundary            = 1,
		.binning_supported                = 0x7,
		.capabilities                     = CAM_IFE_CSID_CAP_SOF_RETIME_DIS |
							CAM_IFE_CSID_CAP_MULTI_CTXT,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_master                = 0x2,
		.start_mode_slave                 = 0x3,
		.sof_retiming_dis_shift           = 5,
		.start_mode_shift                 = 2,
		.start_master_sel_val             = 0,
		.start_master_sel_shift           = 4,
		.crop_v_en_shift_val              = 13,
		.crop_h_en_shift_val              = 12,
		.drop_v_en_shift_val              = 11,
		.drop_h_en_shift_val              = 10,
		.pix_store_en_shift_val           = 0,
		.early_eof_en_shift_val           = 16,
		.bin_h_en_shift_val               = 20,
		.bin_v_en_shift_val               = 21,
		.bin_en_shift_val                 = 18,
		.bin_qcfa_en_shift_val            = 19,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.overflow_ctrl_en                 = 0,
		.overflow_ctrl_mode_val           = 0x8,
		.min_hbi_shift_val                = 4,
		.start_master_sel_shift_val       = 4,
		.bin_pd_en_shift_val              = 0,
		.bin_pd_blk_w_shift_val           = 8,
		.bin_pd_blk_h_shift_val           = 24,
		.bin_pd_detect_x_offset_shift_val = 0,
		.bin_pd_detect_x_end_shift_val    = 16,
		.bin_pd_detect_y_offset_shift_val = 0,
		.bin_pd_detect_y_end_shift_val    = 16,
		.lut_bank_0_sel_val               = 0,
		.lut_bank_1_sel_val               = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x1,
		.aup_mask                         = 0x1,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x100,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.disable_sof_retime_default       = true,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_ipp_1_reg_info = {
		.irq_status_addr                  = 0x01F4,
		.irq_mask_addr                    = 0x01F8,
		.irq_clear_addr                   = 0x01FC,
		.irq_set_addr                     = 0x0200,
		.cfg0_addr                        = 0x1080,
		.ctrl_addr                        = 0x1088,
		.debug_clr_cmd_addr               = 0x108C,
		.multi_vcdt_cfg0_addr             = 0x1090,
		.multi_vcdt_cfg1_addr             = 0x1084,
		.cfg1_addr                        = 0,
		.sparse_pd_extractor_cfg_addr     = 0,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.bin_pd_detect_cfg0_addr          = 0,
		.bin_pd_detect_cfg1_addr          = 0,
		.bin_pd_detect_cfg2_addr	  = 0,
		.camif_frame_cfg_addr             = 0x1094,
		.epoch_irq_cfg_addr               = 0,
		.epoch0_subsample_ptrn_addr       = 0,
		.epoch1_subsample_ptrn_addr       = 0,
		.debug_rup_aup_status             = 0x1098,
		.debug_camif_1_addr               = 0x109C,
		.debug_camif_0_addr               = 0x10A0,
		.frm_drop_pattern_addr            = 0x10B8,
		.frm_drop_period_addr             = 0x10BC,
		.irq_subsample_pattern_addr       = 0x10C0,
		.irq_subsample_period_addr        = 0x10C4,
		.hcrop_addr                       = 0,
		.vcrop_addr                       = 0,
		.pix_drop_pattern_addr            = 0,
		.pix_drop_period_addr             = 0,
		.line_drop_pattern_addr           = 0,
		.line_drop_period_addr            = 0,
		.debug_halt_status_addr           = 0x10A4,
		.debug_misr_val0_addr             = 0x10A8,
		.debug_misr_val1_addr             = 0x10AC,
		.debug_misr_val2_addr             = 0x10B0,
		.debug_misr_val3_addr             = 0x10B4,
		.format_measure_cfg0_addr         = 0x10C8,
		.format_measure_cfg1_addr         = 0x10CC,
		.format_measure_cfg2_addr         = 0x10D0,
		.format_measure0_addr             = 0x10D4,
		.format_measure1_addr             = 0x10D8,
		.format_measure2_addr             = 0x10DC,
		.timestamp_curr0_sof_addr         = 0x10E0,
		.timestamp_curr1_sof_addr         = 0x10E4,
		.timestamp_perv0_sof_addr         = 0x10E8,
		.timestamp_perv1_sof_addr         = 0x10EC,
		.timestamp_curr0_eof_addr         = 0x10F0,
		.timestamp_curr1_eof_addr         = 0x10F4,
		.timestamp_perv0_eof_addr         = 0x10F8,
		.timestamp_perv1_eof_addr         = 0x10FC,
		.lut_bank_cfg_addr                = 0,
		.batch_id_cfg0_addr               = 0x1100,
		.batch_id_cfg1_addr               = 0x1104,
		.batch_period_cfg_addr            = 0x1108,
		.batch_stream_id_cfg_addr         = 0x110C,
		.epoch0_cfg_batch_id0_addr        = 0x1110,
		.epoch1_cfg_batch_id0_addr        = 0x1114,
		.epoch0_cfg_batch_id1_addr        = 0x1118,
		.epoch1_cfg_batch_id1_addr        = 0x111C,
		.epoch0_cfg_batch_id2_addr        = 0x1120,
		.epoch1_cfg_batch_id2_addr        = 0x1124,
		.epoch0_cfg_batch_id3_addr        = 0x1128,
		.epoch1_cfg_batch_id3_addr        = 0x112C,
		.epoch0_cfg_batch_id4_addr        = 0x1130,
		.epoch1_cfg_batch_id4_addr        = 0x1134,
		.epoch0_cfg_batch_id5_addr        = 0x1138,
		.epoch1_cfg_batch_id5_addr        = 0x113C,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x1140,
		.path_frame_id                    = 0x1144,

		/* configurations */
		.resume_frame_boundary            = 1,
		.binning_supported                = 0x7,
		.capabilities                     = CAM_IFE_CSID_CAP_SOF_RETIME_DIS |
							CAM_IFE_CSID_CAP_MULTI_CTXT,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_master                = 0x2,
		.start_mode_slave                 = 0x3,
		.sof_retiming_dis_shift           = 5,
		.start_mode_shift                 = 2,
		.start_master_sel_val             = 0,
		.start_master_sel_shift           = 4,
		.timestamp_en_shift_val           = 6,
		.start_master_sel_shift_val       = 4,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x2,
		.aup_mask                         = 0x2,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x200,},
		.disable_sof_retime_default       = true,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_ipp_2_reg_info = {
		.irq_status_addr                  = 0x0204,
		.irq_mask_addr                    = 0x0208,
		.irq_clear_addr                   = 0x020C,
		.irq_set_addr                     = 0x0210,
		.cfg0_addr                        = 0x1480,
		.ctrl_addr                        = 0x1488,
		.debug_clr_cmd_addr               = 0x148C,
		.multi_vcdt_cfg0_addr             = 0x1490,
		.multi_vcdt_cfg1_addr             = 0x1484,
		.cfg1_addr                        = 0,
		.sparse_pd_extractor_cfg_addr     = 0,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.bin_pd_detect_cfg0_addr          = 0,
		.bin_pd_detect_cfg1_addr          = 0,
		.bin_pd_detect_cfg2_addr	  = 0,
		.camif_frame_cfg_addr             = 0x1494,
		.epoch_irq_cfg_addr               = 0,
		.epoch0_subsample_ptrn_addr       = 0,
		.epoch1_subsample_ptrn_addr       = 0,
		.debug_rup_aup_status             = 0x1498,
		.debug_camif_1_addr               = 0x149C,
		.debug_camif_0_addr               = 0x14A0,
		.frm_drop_pattern_addr            = 0x14B8,
		.frm_drop_period_addr             = 0x14BC,
		.irq_subsample_pattern_addr       = 0x14C0,
		.irq_subsample_period_addr        = 0x14C4,
		.hcrop_addr                       = 0,
		.vcrop_addr                       = 0,
		.pix_drop_pattern_addr            = 0,
		.pix_drop_period_addr             = 0,
		.line_drop_pattern_addr           = 0,
		.line_drop_period_addr            = 0,
		.debug_halt_status_addr           = 0x14A4,
		.debug_misr_val0_addr             = 0x14A8,
		.debug_misr_val1_addr             = 0x14AC,
		.debug_misr_val2_addr             = 0x14B0,
		.debug_misr_val3_addr             = 0x14B4,
		.format_measure_cfg0_addr         = 0x14C8,
		.format_measure_cfg1_addr         = 0x14CC,
		.format_measure_cfg2_addr         = 0x14D0,
		.format_measure0_addr             = 0x14D4,
		.format_measure1_addr             = 0x14D8,
		.format_measure2_addr             = 0x14DC,
		.timestamp_curr0_sof_addr         = 0x14E0,
		.timestamp_curr1_sof_addr         = 0x14E4,
		.timestamp_perv0_sof_addr         = 0x14E8,
		.timestamp_perv1_sof_addr         = 0x14EC,
		.timestamp_curr0_eof_addr         = 0x14F0,
		.timestamp_curr1_eof_addr         = 0x14F4,
		.timestamp_perv0_eof_addr         = 0x14F8,
		.timestamp_perv1_eof_addr         = 0x14FC,
		.lut_bank_cfg_addr                = 0,
		.batch_id_cfg0_addr               = 0x1500,
		.batch_id_cfg1_addr               = 0x1504,
		.batch_period_cfg_addr            = 0x1508,
		.batch_stream_id_cfg_addr         = 0x150C,
		.epoch0_cfg_batch_id0_addr        = 0x1510,
		.epoch1_cfg_batch_id0_addr        = 0x1514,
		.epoch0_cfg_batch_id1_addr        = 0x1518,
		.epoch1_cfg_batch_id1_addr        = 0x151C,
		.epoch0_cfg_batch_id2_addr        = 0x1520,
		.epoch1_cfg_batch_id2_addr        = 0x1524,
		.epoch0_cfg_batch_id3_addr        = 0x1528,
		.epoch1_cfg_batch_id3_addr        = 0x152C,
		.epoch0_cfg_batch_id4_addr        = 0x1530,
		.epoch1_cfg_batch_id4_addr        = 0x1534,
		.epoch0_cfg_batch_id5_addr        = 0x1538,
		.epoch1_cfg_batch_id5_addr        = 0x153C,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x1540,
		.path_frame_id                    = 0x1544,

		/* configurations */
		.resume_frame_boundary            = 1,
		.binning_supported                = 0x7,
		.capabilities                     = CAM_IFE_CSID_CAP_SOF_RETIME_DIS |
							CAM_IFE_CSID_CAP_MULTI_CTXT,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_master                = 0x2,
		.start_mode_slave                 = 0x3,
		.sof_retiming_dis_shift           = 5,
		.start_mode_shift                 = 2,
		.start_master_sel_val             = 0,
		.start_master_sel_shift           = 4,
		.timestamp_en_shift_val           = 6,
		.start_master_sel_shift_val       = 4,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x4,
		.aup_mask                         = 0x4,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x400,},
		.disable_sof_retime_default       = true,
};


static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_ppp_reg_info = {
		.irq_status_addr                  = 0x01D0,
		.irq_mask_addr                    = 0x01D4,
		.irq_clear_addr                   = 0x01D8,
		.irq_set_addr                     = 0x01DC,
		.cfg0_addr                        = 0x3080,
		.ctrl_addr                        = 0x3088,
		.debug_clr_cmd_addr               = 0x308C,
		.multi_vcdt_cfg0_addr             = 0x3090,
		.multi_vcdt_cfg1_addr             = 0x3084,
		.cfg1_addr                        = 0x5080,
		.bin_cfg0_addr                    = 0x3164,
		.pix_store_cfg0_addr              = 0x5084,
		.sparse_pd_extractor_cfg_addr     = 0x5088,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.bin_pd_detect_cfg0_addr          = 0,
		.bin_pd_detect_cfg1_addr          = 0,
		.bin_pd_detect_cfg2_addr	  = 0,
		.camif_frame_cfg_addr             = 0x3094,
		.epoch_irq_cfg_addr               = 0x3154,
		.epoch0_subsample_ptrn_addr       = 0x3158,
		.epoch1_subsample_ptrn_addr       = 0x315C,
		.debug_rup_aup_status             = 0x3098,
		.debug_camif_1_addr               = 0x309C,
		.debug_camif_0_addr               = 0x30A0,
		.frm_drop_pattern_addr            = 0x30B8,
		.frm_drop_period_addr             = 0x30BC,
		.irq_subsample_pattern_addr       = 0x30C0,
		.irq_subsample_period_addr        = 0x30C4,
		.hcrop_addr                       = 0x508C,
		.vcrop_addr                       = 0x5090,
		.pix_drop_pattern_addr            = 0x5094,
		.pix_drop_period_addr             = 0x5098,
		.line_drop_pattern_addr           = 0x509C,
		.line_drop_period_addr            = 0x50A0,
		.debug_halt_status_addr           = 0x30A4,
		.debug_misr_val0_addr             = 0x30A8,
		.debug_misr_val1_addr             = 0x30AC,
		.debug_misr_val2_addr             = 0x30B0,
		.debug_misr_val3_addr             = 0x30B4,
		.format_measure_cfg0_addr         = 0x30C8,
		.format_measure_cfg1_addr         = 0x30CC,
		.format_measure_cfg2_addr         = 0x30D0,
		.format_measure0_addr             = 0x30D4,
		.format_measure1_addr             = 0x30D8,
		.format_measure2_addr             = 0x30DC,
		.timestamp_curr0_sof_addr         = 0x30E0,
		.timestamp_curr1_sof_addr         = 0x30E4,
		.timestamp_perv0_sof_addr         = 0x30E8,
		.timestamp_perv1_sof_addr         = 0x30EC,
		.timestamp_curr0_eof_addr         = 0x30F0,
		.timestamp_curr1_eof_addr         = 0x30F4,
		.timestamp_perv0_eof_addr         = 0x30F8,
		.timestamp_perv1_eof_addr         = 0x30FC,
		.lut_bank_cfg_addr                = 0x50A4,
		.batch_id_cfg0_addr               = 0x3100,
		.batch_id_cfg1_addr               = 0x3104,
		.batch_period_cfg_addr            = 0x3108,
		.batch_stream_id_cfg_addr         = 0x310C,
		.epoch0_cfg_batch_id0_addr        = 0x3110,
		.epoch1_cfg_batch_id0_addr        = 0x3114,
		.epoch0_cfg_batch_id1_addr        = 0x3118,
		.epoch1_cfg_batch_id1_addr        = 0x311C,
		.epoch0_cfg_batch_id2_addr        = 0x3120,
		.epoch1_cfg_batch_id2_addr        = 0x3124,
		.epoch0_cfg_batch_id3_addr        = 0x3128,
		.epoch1_cfg_batch_id3_addr        = 0x312C,
		.epoch0_cfg_batch_id4_addr        = 0x3130,
		.epoch1_cfg_batch_id4_addr        = 0x3134,
		.epoch0_cfg_batch_id5_addr        = 0x3138,
		.epoch1_cfg_batch_id5_addr        = 0x313C,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x3140,
		.path_frame_id                    = 0x3144,
		.debug_sim_monitor                = 0x3168,

		/* configurations */
		.capabilities                     = CAM_IFE_CSID_CAP_SOF_RETIME_DIS,
		.resume_frame_boundary            = 1,
		.start_mode_shift                 = 2,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_master                = 0x2,
		.start_mode_slave                 = 0x3,
		.start_master_sel_val             = 3,
		.start_master_sel_shift           = 4,
		.binning_supported                = 0x1,
		.bin_h_en_shift_val               = 18,
		.bin_en_shift_val                 = 18,
		.early_eof_en_shift_val           = 16,
		.pix_store_en_shift_val           = 0,
		.crop_v_en_shift_val              = 13,
		.crop_h_en_shift_val              = 12,
		.drop_v_en_shift_val              = 11,
		.drop_h_en_shift_val              = 10,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.overflow_ctrl_en                 = 0,
		.overflow_ctrl_mode_val           = 0x8,
		.min_hbi_shift_val                = 1,
		.start_master_sel_shift_val       = 4,
		.lut_bank_0_sel_val               = 0,
		.lut_bank_1_sel_val               = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.rup_mask                         = 0x10000,
		.aup_mask                         = 0x10000,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x10,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.sof_retiming_dis_shift           = 5,
		.disable_sof_retime_default       = true,
		.use_master_slave_default         = true,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_rdi_0_reg_info = {
		.irq_status_addr                  = 0x0224,
		.irq_mask_addr                    = 0x0228,
		.irq_clear_addr                   = 0x022C,
		.irq_set_addr                     = 0x0230,
		.cfg0_addr                        = 0x5480,
		.ctrl_addr                        = 0x5488,
		.debug_clr_cmd_addr               = 0x548C,
		.multi_vcdt_cfg0_addr             = 0x5490,
		.multi_vcdt_cfg1_addr             = 0x5484,
		.cfg1_addr                        = 0x5494,
		.pix_store_cfg0_addr              = 0x5498,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.debug_byte_cntr_ping_addr        = 0x54A8,
		.debug_byte_cntr_pong_addr        = 0x54AC,
		.camif_frame_cfg_addr             = 0x54B0,
		.epoch_irq_cfg_addr               = 0x54B4,
		.epoch0_subsample_ptrn_addr       = 0x54B8,
		.epoch1_subsample_ptrn_addr       = 0x54BC,
		.debug_rup_aup_status             = 0x54C0,
		.debug_camif_1_addr               = 0x54C4,
		.debug_camif_0_addr               = 0x54C8,
		.frm_drop_pattern_addr            = 0x54CC,
		.frm_drop_period_addr             = 0x54D0,
		.irq_subsample_pattern_addr       = 0x54D4,
		.irq_subsample_period_addr        = 0x54D8,
		.hcrop_addr                       = 0x54DC,
		.vcrop_addr                       = 0x54E0,
		.pix_drop_pattern_addr            = 0x54E4,
		.pix_drop_period_addr             = 0x54E8,
		.line_drop_pattern_addr           = 0x54EC,
		.line_drop_period_addr            = 0x54F0,
		.debug_halt_status_addr           = 0x54F8,
		.debug_misr_val0_addr             = 0x54FC,
		.debug_misr_val1_addr             = 0x5500,
		.debug_misr_val2_addr             = 0x5504,
		.debug_misr_val3_addr             = 0x5508,
		.format_measure_cfg0_addr         = 0x550C,
		.format_measure_cfg1_addr         = 0x5510,
		.format_measure_cfg2_addr         = 0x5514,
		.format_measure0_addr             = 0x5518,
		.format_measure1_addr             = 0x551C,
		.format_measure2_addr             = 0x5520,
		.timestamp_curr0_sof_addr         = 0x5524,
		.timestamp_curr1_sof_addr         = 0x5528,
		.timestamp_perv0_sof_addr         = 0x552C,
		.timestamp_perv1_sof_addr         = 0x5530,
		.timestamp_curr0_eof_addr         = 0x5534,
		.timestamp_curr1_eof_addr         = 0x5538,
		.timestamp_perv0_eof_addr         = 0x553C,
		.timestamp_perv1_eof_addr         = 0x5540,
		.batch_id_cfg0_addr               = 0x5544,
		.batch_id_cfg1_addr               = 0x5548,
		.batch_period_cfg_addr            = 0x554C,
		.batch_stream_id_cfg_addr         = 0x5550,
		.epoch0_cfg_batch_id0_addr        = 0x5554,
		.epoch1_cfg_batch_id0_addr        = 0x5558,
		.epoch0_cfg_batch_id1_addr        = 0x555C,
		.epoch1_cfg_batch_id1_addr        = 0x5560,
		.epoch0_cfg_batch_id2_addr        = 0x5564,
		.epoch1_cfg_batch_id2_addr        = 0x5568,
		.epoch0_cfg_batch_id3_addr        = 0x556C,
		.epoch1_cfg_batch_id3_addr        = 0x5570,
		.epoch0_cfg_batch_id4_addr        = 0x5574,
		.epoch1_cfg_batch_id4_addr        = 0x5578,
		.epoch0_cfg_batch_id5_addr        = 0x557C,
		.epoch1_cfg_batch_id5_addr        = 0x5580,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x5584,
		.path_frame_id                    = 0x5588,
		.debug_sim_monitor                = 0x558C,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_en                 = 0,
		.capabilities                     = CAM_IFE_CSID_CAP_INPUT_LCR |
							CAM_IFE_CSID_CAP_RDI_UNPACK_MSB |
							CAM_IFE_CSID_CAP_LINE_SMOOTHING_IN_RDI |
							CAM_IFE_CSID_CAP_SOF_RETIME_DIS,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_shift                 = 2,
		.overflow_ctrl_mode_val           = 0x8,
		.offline_mode_supported           = 1,
		.mipi_pack_supported              = 1,
		.packing_fmt_shift_val            = 15,
		.plain_alignment_shift_val        = 11,
		.plain_fmt_shift_val              = 12,
		.crop_v_en_shift_val              = 8,
		.crop_h_en_shift_val              = 7,
		.drop_v_en_shift_val              = 6,
		.drop_h_en_shift_val              = 5,
		.early_eof_en_shift_val           = 14,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.debug_byte_cntr_rst_shift_val    = 7,
		.offline_mode_en_shift_val        = 2,
		.ccif_violation_en                = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x100,
		.aup_mask                         = 0x100,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x10000,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.pix_store_en_shift_val           = 0,
		.sof_retiming_dis_shift           = 5,
		.default_out_format               = CAM_FORMAT_PLAIN16_16,
		.disable_sof_retime_default       = true,
		.use_master_slave_default         = true,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_rdi_1_reg_info = {
		.irq_status_addr                  = 0x0234,
		.irq_mask_addr                    = 0x0238,
		.irq_clear_addr                   = 0x023C,
		.irq_set_addr                     = 0x0240,
		.cfg0_addr                        = 0x5680,
		.ctrl_addr                        = 0x5688,
		.debug_clr_cmd_addr               = 0x568C,
		.multi_vcdt_cfg0_addr             = 0x5690,
		.multi_vcdt_cfg1_addr             = 0x5684,
		.cfg1_addr                        = 0x5694,
		.pix_store_cfg0_addr              = 0x5698,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.debug_byte_cntr_ping_addr        = 0x56A8,
		.debug_byte_cntr_pong_addr        = 0x56AC,
		.camif_frame_cfg_addr             = 0x56B0,
		.epoch_irq_cfg_addr               = 0x56B4,
		.epoch0_subsample_ptrn_addr       = 0x56B8,
		.epoch1_subsample_ptrn_addr       = 0x56BC,
		.debug_rup_aup_status             = 0x56C0,
		.debug_camif_1_addr               = 0x56C4,
		.debug_camif_0_addr               = 0x56C8,
		.frm_drop_pattern_addr            = 0x56CC,
		.frm_drop_period_addr             = 0x56D0,
		.irq_subsample_pattern_addr       = 0x56D4,
		.irq_subsample_period_addr        = 0x56D8,
		.hcrop_addr                       = 0x56DC,
		.vcrop_addr                       = 0x56E0,
		.pix_drop_pattern_addr            = 0x56E4,
		.pix_drop_period_addr             = 0x56E8,
		.line_drop_pattern_addr           = 0x56EC,
		.line_drop_period_addr            = 0x56F0,
		.debug_halt_status_addr           = 0x56F8,
		.debug_misr_val0_addr             = 0x56FC,
		.debug_misr_val1_addr             = 0x5700,
		.debug_misr_val2_addr             = 0x5704,
		.debug_misr_val3_addr             = 0x5708,
		.format_measure_cfg0_addr         = 0x570C,
		.format_measure_cfg1_addr         = 0x5710,
		.format_measure_cfg2_addr         = 0x5714,
		.format_measure0_addr             = 0x5718,
		.format_measure1_addr             = 0x571C,
		.format_measure2_addr             = 0x5720,
		.timestamp_curr0_sof_addr         = 0x5724,
		.timestamp_curr1_sof_addr         = 0x5728,
		.timestamp_perv0_sof_addr         = 0x572C,
		.timestamp_perv1_sof_addr         = 0x5730,
		.timestamp_curr0_eof_addr         = 0x5734,
		.timestamp_curr1_eof_addr         = 0x5738,
		.timestamp_perv0_eof_addr         = 0x573C,
		.timestamp_perv1_eof_addr         = 0x5740,
		.batch_id_cfg0_addr               = 0x5744,
		.batch_id_cfg1_addr               = 0x5748,
		.batch_period_cfg_addr            = 0x574C,
		.batch_stream_id_cfg_addr         = 0x5750,
		.epoch0_cfg_batch_id0_addr        = 0x5754,
		.epoch1_cfg_batch_id0_addr        = 0x5758,
		.epoch0_cfg_batch_id1_addr        = 0x575C,
		.epoch1_cfg_batch_id1_addr        = 0x5760,
		.epoch0_cfg_batch_id2_addr        = 0x5764,
		.epoch1_cfg_batch_id2_addr        = 0x5768,
		.epoch0_cfg_batch_id3_addr        = 0x576C,
		.epoch1_cfg_batch_id3_addr        = 0x5770,
		.epoch0_cfg_batch_id4_addr        = 0x5774,
		.epoch1_cfg_batch_id4_addr        = 0x5778,
		.epoch0_cfg_batch_id5_addr        = 0x577C,
		.epoch1_cfg_batch_id5_addr        = 0x5780,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x5784,
		.path_frame_id                    = 0x5788,
		.debug_sim_monitor                = 0x578C,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_en                 = 0,
		.capabilities                     = CAM_IFE_CSID_CAP_INPUT_LCR |
							CAM_IFE_CSID_CAP_RDI_UNPACK_MSB |
							CAM_IFE_CSID_CAP_LINE_SMOOTHING_IN_RDI |
							CAM_IFE_CSID_CAP_SOF_RETIME_DIS,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_shift                 = 2,
		.overflow_ctrl_mode_val           = 0x8,
		.offline_mode_supported           = 1,
		.mipi_pack_supported              = 1,
		.packing_fmt_shift_val            = 15,
		.plain_alignment_shift_val        = 11,
		.plain_fmt_shift_val              = 12,
		.crop_v_en_shift_val              = 8,
		.crop_h_en_shift_val              = 7,
		.drop_v_en_shift_val              = 6,
		.drop_h_en_shift_val              = 5,
		.early_eof_en_shift_val           = 14,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.debug_byte_cntr_rst_shift_val    = 7,
		.offline_mode_en_shift_val        = 2,
		.ccif_violation_en                = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x200,
		.aup_mask                         = 0x200,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x20000,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.pix_store_en_shift_val           = 0,
		.sof_retiming_dis_shift           = 5,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_rdi_2_reg_info = {
		.irq_status_addr                  = 0x0244,
		.irq_mask_addr                    = 0x0248,
		.irq_clear_addr                   = 0x024C,
		.irq_set_addr                     = 0x0250,
		.cfg0_addr                        = 0x5880,
		.ctrl_addr                        = 0x5888,
		.debug_clr_cmd_addr               = 0x588C,
		.multi_vcdt_cfg0_addr             = 0x5890,
		.multi_vcdt_cfg1_addr             = 0x5884,
		.cfg1_addr                        = 0x5894,
		.pix_store_cfg0_addr              = 0x5898,
		.err_recovery_cfg0_addr           = 0,
		.err_recovery_cfg1_addr           = 0,
		.err_recovery_cfg2_addr           = 0,
		.debug_byte_cntr_ping_addr        = 0x58A8,
		.debug_byte_cntr_pong_addr        = 0x58AC,
		.camif_frame_cfg_addr             = 0x58B0,
		.epoch_irq_cfg_addr               = 0x58B4,
		.epoch0_subsample_ptrn_addr       = 0x58B8,
		.epoch1_subsample_ptrn_addr       = 0x58BC,
		.debug_rup_aup_status             = 0x58C0,
		.debug_camif_1_addr               = 0x58C4,
		.debug_camif_0_addr               = 0x58C8,
		.frm_drop_pattern_addr            = 0x58CC,
		.frm_drop_period_addr             = 0x58D0,
		.irq_subsample_pattern_addr       = 0x58D4,
		.irq_subsample_period_addr        = 0x58D8,
		.hcrop_addr                       = 0x58DC,
		.vcrop_addr                       = 0x58E0,
		.pix_drop_pattern_addr            = 0x58E4,
		.pix_drop_period_addr             = 0x58E8,
		.line_drop_pattern_addr           = 0x58EC,
		.line_drop_period_addr            = 0x58F0,
		.debug_halt_status_addr           = 0x58F8,
		.debug_misr_val0_addr             = 0x58FC,
		.debug_misr_val1_addr             = 0x5900,
		.debug_misr_val2_addr             = 0x5904,
		.debug_misr_val3_addr             = 0x5908,
		.format_measure_cfg0_addr         = 0x590C,
		.format_measure_cfg1_addr         = 0x5910,
		.format_measure_cfg2_addr         = 0x5914,
		.format_measure0_addr             = 0x5918,
		.format_measure1_addr             = 0x591C,
		.format_measure2_addr             = 0x5920,
		.timestamp_curr0_sof_addr         = 0x5924,
		.timestamp_curr1_sof_addr         = 0x5928,
		.timestamp_perv0_sof_addr         = 0x592C,
		.timestamp_perv1_sof_addr         = 0x5930,
		.timestamp_curr0_eof_addr         = 0x5934,
		.timestamp_curr1_eof_addr         = 0x5938,
		.timestamp_perv0_eof_addr         = 0x593C,
		.timestamp_perv1_eof_addr         = 0x5940,
		.batch_id_cfg0_addr               = 0x5944,
		.batch_id_cfg1_addr               = 0x5948,
		.batch_period_cfg_addr            = 0x594C,
		.batch_stream_id_cfg_addr         = 0x5950,
		.epoch0_cfg_batch_id0_addr        = 0x5954,
		.epoch1_cfg_batch_id0_addr        = 0x5958,
		.epoch0_cfg_batch_id1_addr        = 0x595C,
		.epoch1_cfg_batch_id1_addr        = 0x5960,
		.epoch0_cfg_batch_id2_addr        = 0x5964,
		.epoch1_cfg_batch_id2_addr        = 0x5968,
		.epoch0_cfg_batch_id3_addr        = 0x596C,
		.epoch1_cfg_batch_id3_addr        = 0x5970,
		.epoch0_cfg_batch_id4_addr        = 0x5974,
		.epoch1_cfg_batch_id4_addr        = 0x5978,
		.epoch0_cfg_batch_id5_addr        = 0x597C,
		.epoch1_cfg_batch_id5_addr        = 0x5980,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x5984,
		.path_frame_id                    = 0x5988,
		.debug_sim_monitor                = 0x598C,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_en                 = 0,
		.capabilities                     = CAM_IFE_CSID_CAP_INPUT_LCR |
							CAM_IFE_CSID_CAP_RDI_UNPACK_MSB |
							CAM_IFE_CSID_CAP_LINE_SMOOTHING_IN_RDI |
							CAM_IFE_CSID_CAP_SOF_RETIME_DIS,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_shift                 = 2,
		.overflow_ctrl_mode_val           = 0x8,
		.offline_mode_supported           = 1,
		.mipi_pack_supported              = 1,
		.packing_fmt_shift_val            = 15,
		.plain_alignment_shift_val        = 11,
		.plain_fmt_shift_val              = 12,
		.crop_v_en_shift_val              = 8,
		.crop_h_en_shift_val              = 7,
		.drop_v_en_shift_val              = 6,
		.drop_h_en_shift_val              = 5,
		.early_eof_en_shift_val           = 14,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.debug_byte_cntr_rst_shift_val    = 7,
		.offline_mode_en_shift_val        = 2,
		.ccif_violation_en                = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x400,
		.aup_mask                         = 0x400,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x40000,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.pix_store_en_shift_val           = 0,
		.sof_retiming_dis_shift           = 5,

};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_rdi_3_reg_info = {
		.irq_status_addr                  = 0x0254,
		.irq_mask_addr                    = 0x0258,
		.irq_clear_addr                   = 0x025C,
		.irq_set_addr                     = 0x0260,
		.cfg0_addr                        = 0x5A80,
		.ctrl_addr                        = 0x5A88,
		.debug_clr_cmd_addr               = 0x5A8C,
		.multi_vcdt_cfg0_addr             = 0x5A90,
		.multi_vcdt_cfg1_addr             = 0x5A84,
		.cfg1_addr                        = 0x5A94,
		.debug_byte_cntr_ping_addr        = 0x5AA8,
		.debug_byte_cntr_pong_addr        = 0x5AAC,
		.camif_frame_cfg_addr             = 0x5AB0,
		.epoch_irq_cfg_addr               = 0x5AB4,
		.epoch0_subsample_ptrn_addr       = 0x5AB8,
		.epoch1_subsample_ptrn_addr       = 0x5ABC,
		.debug_rup_aup_status             = 0x5AC0,
		.debug_camif_1_addr               = 0x5AC4,
		.debug_camif_0_addr               = 0x5AC8,
		.frm_drop_pattern_addr            = 0x5ACC,
		.frm_drop_period_addr             = 0x5AD0,
		.irq_subsample_pattern_addr       = 0x5AD4,
		.irq_subsample_period_addr        = 0x5AD8,
		.hcrop_addr                       = 0x5ADC,
		.vcrop_addr                       = 0x5AE0,
		.pix_drop_pattern_addr            = 0x5AE4,
		.pix_drop_period_addr             = 0x5AE8,
		.line_drop_pattern_addr           = 0x5AEC,
		.line_drop_period_addr            = 0x5AF0,
		.debug_halt_status_addr           = 0x5AF8,
		.debug_misr_val0_addr             = 0x5AFC,
		.debug_misr_val1_addr             = 0x5B00,
		.debug_misr_val2_addr             = 0x5B04,
		.debug_misr_val3_addr             = 0x5B08,
		.format_measure_cfg0_addr         = 0x5B0C,
		.format_measure_cfg1_addr         = 0x5B10,
		.format_measure_cfg2_addr         = 0x5B14,
		.format_measure0_addr             = 0x5B18,
		.format_measure1_addr             = 0x5B1C,
		.format_measure2_addr             = 0x5B20,
		.timestamp_curr0_sof_addr         = 0x5B24,
		.timestamp_curr1_sof_addr         = 0x5B28,
		.timestamp_perv0_sof_addr         = 0x5B2C,
		.timestamp_perv1_sof_addr         = 0x5B30,
		.timestamp_curr0_eof_addr         = 0x5B34,
		.timestamp_curr1_eof_addr         = 0x5B38,
		.timestamp_perv0_eof_addr         = 0x5B3C,
		.timestamp_perv1_eof_addr         = 0x5B40,
		.batch_id_cfg0_addr               = 0x5B44,
		.batch_id_cfg1_addr               = 0x5B48,
		.batch_period_cfg_addr            = 0x5B4C,
		.batch_stream_id_cfg_addr         = 0x5B50,
		.epoch0_cfg_batch_id0_addr        = 0x5B54,
		.epoch1_cfg_batch_id0_addr        = 0x5B58,
		.epoch0_cfg_batch_id1_addr        = 0x5B5C,
		.epoch1_cfg_batch_id1_addr        = 0x5B60,
		.epoch0_cfg_batch_id2_addr        = 0x5B64,
		.epoch1_cfg_batch_id2_addr        = 0x5B68,
		.epoch0_cfg_batch_id3_addr        = 0x5B6C,
		.epoch1_cfg_batch_id3_addr        = 0x5B70,
		.epoch0_cfg_batch_id4_addr        = 0x5B74,
		.epoch1_cfg_batch_id4_addr        = 0x5B78,
		.epoch0_cfg_batch_id5_addr        = 0x5B7C,
		.epoch1_cfg_batch_id5_addr        = 0x5B80,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x5B84,
		.path_frame_id                    = 0x5B88,
		.debug_sim_monitor                = 0x5B8C,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_en                 = 0,
		.capabilities                     = CAM_IFE_CSID_CAP_INPUT_LCR |
							CAM_IFE_CSID_CAP_RDI_UNPACK_MSB |
							CAM_IFE_CSID_CAP_LINE_SMOOTHING_IN_RDI |
							CAM_IFE_CSID_CAP_SOF_RETIME_DIS,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_shift                 = 2,
		.overflow_ctrl_mode_val           = 0x8,
		.offline_mode_supported           = 1,
		.mipi_pack_supported              = 1,
		.packing_fmt_shift_val            = 15,
		.plain_alignment_shift_val        = 11,
		.plain_fmt_shift_val              = 12,
		.crop_v_en_shift_val              = 8,
		.crop_h_en_shift_val              = 7,
		.drop_v_en_shift_val              = 6,
		.drop_h_en_shift_val              = 5,
		.early_eof_en_shift_val           = 14,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.debug_byte_cntr_rst_shift_val    = 7,
		.offline_mode_en_shift_val        = 2,
		.ccif_violation_en                = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x800,
		.aup_mask                         = 0x800,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x80000,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.pix_store_en_shift_val           = 0,
		.sof_retiming_dis_shift           = 5,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_1080_rdi_4_reg_info = {
		.irq_status_addr                  = 0x0264,
		.irq_mask_addr                    = 0x0268,
		.irq_clear_addr                   = 0x026C,
		.irq_set_addr                     = 0x0270,
		.cfg0_addr                        = 0x5C80,
		.ctrl_addr                        = 0x5C88,
		.debug_clr_cmd_addr               = 0x5C8C,
		.multi_vcdt_cfg0_addr             = 0x5C90,
		.multi_vcdt_cfg1_addr             = 0x5C84,
		.cfg1_addr                        = 0x5C94,
		.debug_byte_cntr_ping_addr        = 0x5CA8,
		.debug_byte_cntr_pong_addr        = 0x5CAC,
		.camif_frame_cfg_addr             = 0x5CB0,
		.epoch_irq_cfg_addr               = 0x5CB4,
		.epoch0_subsample_ptrn_addr       = 0x5CB8,
		.epoch1_subsample_ptrn_addr       = 0x5CBC,
		.debug_rup_aup_status             = 0x5CC0,
		.debug_camif_1_addr               = 0x5CC4,
		.debug_camif_0_addr               = 0x5CC8,
		.frm_drop_pattern_addr            = 0x5CCC,
		.frm_drop_period_addr             = 0x5CD0,
		.irq_subsample_pattern_addr       = 0x5CD4,
		.irq_subsample_period_addr        = 0x5CD8,
		.hcrop_addr                       = 0x5CDC,
		.vcrop_addr                       = 0x5CE0,
		.pix_drop_pattern_addr            = 0x5CE4,
		.pix_drop_period_addr             = 0x5CE8,
		.line_drop_pattern_addr           = 0x5CEC,
		.line_drop_period_addr            = 0x5CF0,
		.debug_halt_status_addr           = 0x5CF8,
		.debug_misr_val0_addr             = 0x5CFC,
		.debug_misr_val1_addr             = 0x5D00,
		.debug_misr_val2_addr             = 0x5D04,
		.debug_misr_val3_addr             = 0x5D08,
		.format_measure_cfg0_addr         = 0x5D0C,
		.format_measure_cfg1_addr         = 0x5D10,
		.format_measure_cfg2_addr         = 0x5D14,
		.format_measure0_addr             = 0x5D18,
		.format_measure1_addr             = 0x5D1C,
		.format_measure2_addr             = 0x5D20,
		.timestamp_curr0_sof_addr         = 0x5D24,
		.timestamp_curr1_sof_addr         = 0x5D28,
		.timestamp_perv0_sof_addr         = 0x5D2C,
		.timestamp_perv1_sof_addr         = 0x5D30,
		.timestamp_curr0_eof_addr         = 0x5D34,
		.timestamp_curr1_eof_addr         = 0x5D38,
		.timestamp_perv0_eof_addr         = 0x5D3C,
		.timestamp_perv1_eof_addr         = 0x5D40,
		.batch_id_cfg0_addr               = 0x5D44,
		.batch_id_cfg1_addr               = 0x5D48,
		.batch_period_cfg_addr            = 0x5D4C,
		.batch_stream_id_cfg_addr         = 0x5D50,
		.epoch0_cfg_batch_id0_addr        = 0x5D54,
		.epoch1_cfg_batch_id0_addr        = 0x5D58,
		.epoch0_cfg_batch_id1_addr        = 0x5D5C,
		.epoch1_cfg_batch_id1_addr        = 0x5D60,
		.epoch0_cfg_batch_id2_addr        = 0x5D64,
		.epoch1_cfg_batch_id2_addr        = 0x5D68,
		.epoch0_cfg_batch_id3_addr        = 0x5D6C,
		.epoch1_cfg_batch_id3_addr        = 0x5D70,
		.epoch0_cfg_batch_id4_addr        = 0x5D74,
		.epoch1_cfg_batch_id4_addr        = 0x5D78,
		.epoch0_cfg_batch_id5_addr        = 0x5D7c,
		.epoch1_cfg_batch_id5_addr        = 0x5D80,
		.secure_mask_cfg0                 = 0,
		.path_batch_status                = 0x5D84,
		.path_frame_id                    = 0x5D88,
		.debug_sim_monitor                = 0x5D8C,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_en                 = 0,
		.capabilities                     = CAM_IFE_CSID_CAP_INPUT_LCR |
							CAM_IFE_CSID_CAP_RDI_UNPACK_MSB |
							CAM_IFE_CSID_CAP_LINE_SMOOTHING_IN_RDI |
							CAM_IFE_CSID_CAP_SOF_RETIME_DIS,
		.start_mode_internal              = 0x0,
		.start_mode_global                = 0x1,
		.start_mode_shift                 = 2,
		.overflow_ctrl_mode_val           = 0x8,
		.offline_mode_supported           = 1,
		.mipi_pack_supported              = 1,
		.packing_fmt_shift_val            = 15,
		.plain_alignment_shift_val        = 11,
		.plain_fmt_shift_val              = 12,
		.crop_v_en_shift_val              = 8,
		.crop_h_en_shift_val              = 7,
		.drop_v_en_shift_val              = 6,
		.drop_h_en_shift_val              = 5,
		.early_eof_en_shift_val           = 14,
		.format_measure_en_shift_val      = 4,
		.timestamp_en_shift_val           = 6,
		.debug_byte_cntr_rst_shift_val    = 7,
		.offline_mode_en_shift_val        = 2,
		.ccif_violation_en                = 1,
		.fatal_err_mask                   = 0x2c1c6081,
		.non_fatal_err_mask               = 0x12000000,
		.sof_irq_mask                     = 0x10,
		.rup_irq_mask                     = 0x800000,
		.epoch0_irq_mask                  = 0x200000,
		.epoch1_irq_mask                  = 0x400000,
		.eof_irq_mask                     = 0x8,
		.rup_mask                         = 0x1000,
		.aup_mask                         = 0x1000,
		.rup_aup_set_mask                 = 0x1,
		.top_irq_mask                     = {0x100000,},
		.epoch0_shift_val                 = 16,
		.epoch1_shift_val                 = 0,
		.pix_store_en_shift_val           = 0,
		.sof_retiming_dis_shift           = 5,
};

static struct cam_ife_csid_rx_debug_mask cam_ife_csid_1080_rx_debug_mask = {

	.evt_bitmap = {
		BIT_ULL(CAM_IFE_CSID_RX_DL0_EOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL1_EOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL2_EOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL3_EOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL0_SOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL1_SOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL2_SOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_DL3_SOT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_WARNING_ECC) |
			BIT_ULL(CAM_IFE_CSID_RX_ERROR_CPHY_PH_CRC) |
			BIT_ULL(CAM_IFE_CSID_RX_LANE0_FIFO_OVERFLOW) |
			BIT_ULL(CAM_IFE_CSID_RX_LANE1_FIFO_OVERFLOW) |
			BIT_ULL(CAM_IFE_CSID_RX_LANE2_FIFO_OVERFLOW) |
			BIT_ULL(CAM_IFE_CSID_RX_LANE3_FIFO_OVERFLOW) |
			BIT_ULL(CAM_IFE_CSID_RX_ERROR_CRC) |
			BIT_ULL(CAM_IFE_CSID_RX_ERROR_ECC) |
			BIT_ULL(CAM_IFE_CSID_RX_MMAPPED_VC_DT) |
			BIT_ULL(CAM_IFE_CSID_RX_UNMAPPED_VC_DT) |
			BIT_ULL(CAM_IFE_CSID_RX_STREAM_UNDERFLOW) |
			BIT_ULL(CAM_IFE_CSID_RX_RX2_IRQ) |
			BIT_ULL(CAM_IFE_CSID_RX_DL0_EOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL1_EOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL2_EOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL3_EOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL0_SOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL1_SOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL2_SOT_LOST) |
			BIT_ULL(CAM_IFE_CSID_RX_DL3_SOT_LOST),

		BIT_ULL(CAM_IFE_CSID_RX_LONG_PKT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_SHORT_PKT_CAPTURED) |
			BIT_ULL(CAM_IFE_CSID_RX_CPHY_PKT_HDR_CAPTURED),
	},


	.bit_pos[CAM_IFE_CSID_RX_DL0_EOT_CAPTURED] = 0,
	.bit_pos[CAM_IFE_CSID_RX_DL1_EOT_CAPTURED] = 1,
	.bit_pos[CAM_IFE_CSID_RX_DL2_EOT_CAPTURED] = 2,
	.bit_pos[CAM_IFE_CSID_RX_DL3_EOT_CAPTURED] = 3,
	.bit_pos[CAM_IFE_CSID_RX_DL0_SOT_CAPTURED] = 4,
	.bit_pos[CAM_IFE_CSID_RX_DL1_SOT_CAPTURED] = 5,
	.bit_pos[CAM_IFE_CSID_RX_DL2_SOT_CAPTURED] = 6,
	.bit_pos[CAM_IFE_CSID_RX_DL3_SOT_CAPTURED] = 7,
	.bit_pos[CAM_IFE_CSID_RX_WARNING_ECC] = 8,
	.bit_pos[CAM_IFE_CSID_RX_LONG_PKT_CAPTURED] = 0,
	.bit_pos[CAM_IFE_CSID_RX_SHORT_PKT_CAPTURED] = 1,
	.bit_pos[CAM_IFE_CSID_RX_CPHY_PKT_HDR_CAPTURED] = 2,
	.bit_pos[CAM_IFE_CSID_RX_ERROR_CPHY_PH_CRC] = 24,
	.bit_pos[CAM_IFE_CSID_RX_LANE0_FIFO_OVERFLOW] = 20,
	.bit_pos[CAM_IFE_CSID_RX_LANE1_FIFO_OVERFLOW] = 21,
	.bit_pos[CAM_IFE_CSID_RX_LANE2_FIFO_OVERFLOW] = 22,
	.bit_pos[CAM_IFE_CSID_RX_LANE3_FIFO_OVERFLOW] = 23,
	.bit_pos[CAM_IFE_CSID_RX_ERROR_CRC] = 25,
	.bit_pos[CAM_IFE_CSID_RX_ERROR_ECC] = 26,
	.bit_pos[CAM_IFE_CSID_RX_MMAPPED_VC_DT] = 27,
	.bit_pos[CAM_IFE_CSID_RX_UNMAPPED_VC_DT] = 28,
	.bit_pos[CAM_IFE_CSID_RX_STREAM_UNDERFLOW] = 29,
	.bit_pos[CAM_IFE_CSID_RX_RX2_IRQ] = 31,
	.bit_pos[CAM_IFE_CSID_RX_DL0_EOT_LOST] = 12,
	.bit_pos[CAM_IFE_CSID_RX_DL1_EOT_LOST] = 13,
	.bit_pos[CAM_IFE_CSID_RX_DL2_EOT_LOST] = 14,
	.bit_pos[CAM_IFE_CSID_RX_DL3_EOT_LOST] = 15,
	.bit_pos[CAM_IFE_CSID_RX_DL0_SOT_LOST] = 16,
	.bit_pos[CAM_IFE_CSID_RX_DL1_SOT_LOST] = 17,
	.bit_pos[CAM_IFE_CSID_RX_DL2_SOT_LOST] = 18,
	.bit_pos[CAM_IFE_CSID_RX_DL3_SOT_LOST] = 19,
};

static struct cam_ife_csid_top_debug_mask cam_ife_csid_1080_top_debug_mask = {

	.evt_bitmap = {
		0ULL,

		BIT_ULL(CAM_IFE_CSID_TOP_INFO_VOTE_UP) |
			BIT_ULL(CAM_IFE_CSID_TOP_INFO_VOTE_DN) |
			BIT_ULL(CAM_IFE_CSID_TOP_ERR_NO_VOTE_DN),
	},

	.bit_pos[CAM_IFE_CSID_TOP_INFO_VOTE_UP] = 0,
	.bit_pos[CAM_IFE_CSID_TOP_INFO_VOTE_DN] = 1,
	.bit_pos[CAM_IFE_CSID_TOP_ERR_NO_VOTE_DN] = 2,
};


static struct cam_ife_csid_ver2_csi2_rx_reg_info
	cam_ife_csid_1080_csi2_reg_info = {
		.irq_status_addr                 = {0x01B0, 0x01C0},
		.irq_mask_addr                   = {0x01B4, 0x01C4},
		.irq_clear_addr                  = {0x01B8, 0x01C8},
		.irq_set_addr                    = {0x01BC, 0x01CC},
		/*CSI2 rx control */
		.cfg0_addr                       = 0x0880,
		.cfg1_addr                       = 0x0884,
		.capture_ctrl_addr               = 0x0888,
		.rst_strobes_addr                = 0x088C,
		.cap_unmap_long_pkt_hdr_0_addr   = 0x0890,
		.cap_unmap_long_pkt_hdr_1_addr   = 0x0894,
		.captured_short_pkt_0_addr       = 0x0898,
		.captured_short_pkt_1_addr       = 0x089C,
		.captured_long_pkt_0_addr        = 0x08A0,
		.captured_long_pkt_1_addr        = 0x08A4,
		.captured_long_pkt_ftr_addr      = 0x08A8,
		.captured_cphy_pkt_hdr_addr      = 0x08AC,
		.lane0_misr_addr                 = 0x08B0,
		.lane1_misr_addr                 = 0x08B4,
		.lane2_misr_addr                 = 0x08B8,
		.lane3_misr_addr                 = 0x08BC,
		.total_pkts_rcvd_addr            = 0x08C0,
		.stats_ecc_addr                  = 0x08C4,
		.total_crc_err_addr              = 0x08C8,
		.de_scramble_type3_cfg0_addr     = 0x08CC,
		.de_scramble_type3_cfg1_addr     = 0x08D0,
		.de_scramble_type2_cfg0_addr     = 0x08D4,
		.de_scramble_type2_cfg1_addr     = 0x08D8,
		.de_scramble_type1_cfg0_addr     = 0x08DC,
		.de_scramble_type1_cfg1_addr     = 0x08E0,
		.de_scramble_type0_cfg0_addr     = 0x08E4,
		.de_scramble_type0_cfg1_addr     = 0x08E8,

		.rst_done_shift_val              = 27,
		.irq_mask_all                    = 0xFFFFFFF,
		.misr_enable_shift_val           = 6,
		.vc_mode_shift_val               = 2,
		.capture_long_pkt_en_shift       = 0,
		.capture_short_pkt_en_shift      = 1,
		.capture_cphy_pkt_en_shift       = 2,
		.capture_long_pkt_dt_shift       = 4,
		.capture_long_pkt_vc_shift       = 10,
		.capture_short_pkt_vc_shift      = 15,
		.capture_cphy_pkt_dt_shift       = 20,
		.capture_cphy_pkt_vc_shift       = 26,
		.phy_num_mask                    = 0xf,
		.vc_mask                         = 0x7C00000,
		.dt_mask                         = 0x3f0000,
		.wc_mask                         = 0xffff,
		.vc_shift                        = 0x16,
		.dt_shift                        = 0x10,
		.wc_shift                        = 0,
		.calc_crc_mask                   = 0xffff0000,
		.expected_crc_mask               = 0xffff,
		.calc_crc_shift                  = 0x10,
		.ecc_correction_shift_en         = 0,
		.lane_num_shift                  = 0,
		.lane_cfg_shift                  = 4,
		.phy_type_shift                  = 24,
		.phy_num_shift                   = 20,
		.tpg_mux_en_shift                = 27,
		.tpg_num_sel_shift               = 28,
		.phy_bist_shift_en               = 7,
		.epd_mode_shift_en               = 8,
		.eotp_shift_en                   = 9,
		.dyn_sensor_switch_shift_en      = 10,
		.rup_aup_latch_shift             = 13,
		.rup_aup_latch_supported         = true,
		.long_pkt_strobe_rst_shift       = 0,
		.short_pkt_strobe_rst_shift      = 1,
		.cphy_pkt_strobe_rst_shift       = 2,
		.unmapped_pkt_strobe_rst_shift   = 3,
		.fatal_err_mask                  = {0x25fff000, 0x0},
		.part_fatal_err_mask             = {0x02000000, 0x0},
		.non_fatal_err_mask              = {0x08000000, 0x0},
		.top_irq_mask                    = {0x4, 0x0},
		.rx_rx2_irq_mask                 = 0x80000000,
};

static struct cam_ife_csid_ver2_common_reg_info
			cam_ife_csid_1080_cmn_reg_info = {
	.hw_version_addr                         = 0x0000,
	.cfg0_addr                               = 0x0100,
	.global_cmd_addr                         = 0x0104,
	.reset_cfg_addr                          = 0x0108,
	.reset_cmd_addr                          = 0x010C,
	.irq_cmd_addr                            = 0x0110,
	.rup_cmd_addr                            = 0x0114,
	.aup_cmd_addr                            = 0x0118,
	.rup_aup_cmd_addr                        = 0x011C,
	.offline_cmd_addr                        = 0x0120,
	.shdr_master_slave_cfg_addr              = 0x0124,
	.multi_sensor_mode_addr                  = 0x0128,
	.top_irq_status_addr                     = {0x0180, 0x0190},
	.top_irq_mask_addr                       = {0x0184, 0x0194},
	.top_irq_clear_addr                      = {0x0188, 0x0198},
	.top_irq_set_addr                        = {0x018C, 0x019C},
	.buf_done_irq_status_addr                = 0x01A0,
	.buf_done_irq_mask_addr                  = 0x01A4,
	.buf_done_irq_clear_addr                 = 0x01A8,
	.buf_done_irq_set_addr                   = 0x01AC,
	.test_bus_ctrl                           = 0x07DC,
	.test_bus_debug                          = 0x07F8,
	.drv_cfg0_addr                           = 0x0800,
	.drv_cfg1_addr                           = 0x0804,
	.drv_cfg2_addr                           = 0x0808,
	.debug_drv_0_addr                        = 0x080C,
	.debug_drv_1_addr                        = 0x0810,
	.debug_sensor_hbi_irq_vcdt_addr          = 0x29C,
	.debug_violation_addr                    = 0x7E0,
	.debug_cfg_addr                          = 0x7E4,
	.debug_err_vec_irq                       = {0x2D4, 0x2D8, 0x2DC},
	.debug_err_vec_cfg                       = 0x2D0,
	.debug_err_vec_ts_lb                     = 0x2E0,
	.debug_err_vec_ts_mb                     = 0x2E4,
	.rx_mode_id_cfg1_addr                    = 0x0870,

	/*configurations */
	.major_version                           = 10,
	.minor_version                           = 8,
	.version_incr                            = 0,
	.num_rdis                                = 5,
	.num_pix                                 = 3,
	.num_ppp                                 = 1,
	.rst_done_shift_val                      = 1,
	.path_en_shift_val                       = 31,
	.vc_shift_val                            = 22,
	.vc_mask                                 = 0x1F,
	.dt_shift_val                            = 16,
	.dt_mask                                 = 0x3F,
	.crop_shift_val                          = 16,
	.decode_format_shift_val                 = 12,
	.decode_format1_shift_val                = 16,
	.decode_format2_shift_val                = 0,
	.decode_format3_shift_val                = 4,
	.decode_format1_supported                = true,
	.decode_format_mask                      = 0xF,
	.frame_id_decode_en_shift_val            = 1,
	.multi_vcdt_vc1_shift_val                = 2,
	.multi_vcdt_dt1_shift_val                = 7,
	.multi_vcdt_dt2_shift_val                = 8,
	.multi_vcdt_dt3_shift_val                = 16,
	.multi_vcdt_ts_combo_en_shift_val        = 13,
	.multi_vcdt_en_shift_val                 = 0,
	.timestamp_stb_sel_shift_val             = 8,
	.vfr_en_shift_val                        = 0,
	.mup_shift_val                           = 4,
	.shdr_slave_ppp_shift                    = 16,
	.shdr_slave_rdi2_shift                   = 18,
	.shdr_slave_rdi1_shift                   = 17,
	.shdr_master_rdi0_shift                  = 4,
	.shdr_master_slave_en_shift              = 0,
	.drv_en_shift                            = 0,
	.drv_rup_en_shift                        = 0,
	.early_eof_supported                     = 1,
	.vfr_supported                           = 1,
	.multi_vcdt_supported                    = 1,
	.num_dt_supported                        = 4,
	.ts_comb_vcdt_en                         = true,
	.direct_cid_config                       = true,
	.ts_comb_vcdt_mask                       = 3,
	.frame_id_dec_supported                  = 1,
	.measure_en_hbi_vbi_cnt_mask             = 0xc,
	.measure_pixel_line_en_mask              = 0x3,
	.crop_pix_start_mask                     = 0x3fff,
	.crop_pix_end_mask                       = 0xffff,
	.crop_line_start_mask                    = 0x3fff,
	.crop_line_end_mask                      = 0xffff,
	.drop_supported                          = 1,
	.ipp_irq_mask_all                        = 0x7FFF,
	.rdi_irq_mask_all                        = 0x7FFF,
	.ppp_irq_mask_all                        = 0xFFFF,
	.top_err_irq_mask                        = {0x00000002, 0x18},
	.rst_loc_path_only_val                   = 0x0,
	.rst_loc_complete_csid_val               = 0x1,
	.rst_mode_frame_boundary_val             = 0x0,
	.rst_mode_immediate_val                  = 0x1,
	.rst_cmd_hw_reset_complete_val           = 0x1,
	.rst_cmd_sw_reset_complete_val           = 0x2,
	.rst_cmd_irq_ctrl_only_val               = 0x4,
	.timestamp_strobe_val                    = 0x2,
	.top_reset_irq_mask                      = {0x1,},
	.rst_location_shift_val                  = 4,
	.rst_mode_shift_val                      = 0,
	.epoch_factor                            = 50,
	.global_reset                            = 1,
	.aup_rup_supported                       = 1,
	.only_master_rup                         = 1,
	.format_measure_height_mask_val          = 0xFFFF,
	.format_measure_height_shift_val         = 0x10,
	.format_measure_width_mask_val           = 0xFFFF,
	.format_measure_width_shift_val          = 0x0,
	.format_measure_max_hbi_shift            = 16,
	.format_measure_min_hbi_mask             = 0xFFF,
	.top_buf_done_irq_mask                   = 0x8,
	.decode_format_payload_only              = 0xF,
	.timestamp_enabled_in_cfg0               = true,
	.camif_irq_support                       = true,
	.capabilities                            = CAM_IFE_CSID_CAP_SPLIT_RUP_AUP |
							CAM_IFE_CSID_CAP_SKIP_PATH_CFG1 |
							CAM_IFE_CSID_CAP_SKIP_EPOCH_CFG |
							CAM_IFE_CSID_CAP_DEBUG_ERR_VEC |
							CAM_IFE_CSID_CAP_TOP_MASK_ALL_IRQS,
	.top_top2_irq_mask                       = 0x80000000,
	.drv_rup_en_val_map = {
		2, /*RDI0 */
		3, /*RDI1 */
		4, /*RDI2 */
		5, /*RDI3 */
		6, /*RDI4 */
		0, /*IPP */
		1, /*PPP */
		0, /*UDI0 */
		0, /*UDI1 */
		0, /*UDI2 */
	},
	.drv_path_idle_en_val_map = {
		BIT(4), /*CAM_ISP_PXL_PATH */
		BIT(5), /*CAM_ISP_PPP_PATH */
		0,      /* LCR not applicable */
		BIT(6), /*CAM_ISP_RDI0_PATH */
		BIT(7), /*CAM_ISP_RDI1_PATH */
		BIT(8), /*CAM_ISP_RDI2_PATH */
		BIT(9), /*CAM_ISP_RDI3_PATH */
		BIT(10), /*CAM_ISP_RDI4_PATH */
	},
	.path_domain_id_cfg0                     = 0x0,
	.path_domain_id_cfg1                     = 0x4,
	.path_domain_id_cfg2                     = 0x8,
	.phy_sel_base_idx                        = 1,
};

struct cam_ife_csid_ver2_mc_reg_info
	cam_ife_csid_1080_ipp_mc_reg_info = {
	.irq_comp_cfg0_addr                = 0x0294,
	.ipp_src_ctxt_mask_shift           = 4,
	.ipp_dst_ctxt_mask_shift           = 0,
	.comp_rup_mask                     = 0x4000000,
	.comp_epoch0_mask                  = 0x8000000,
	.comp_eof_mask                     = 0x20000000,
	.comp_sof_mask                     = 0x40000000,
	.comp_subgrp0_mask                 = 0x1000000,
	.comp_subgrp2_mask                 = 0x2000000,
};

static struct cam_ife_csid_ver2_reg_info cam_ife_csid_1080_reg_info = {
	.top_irq_reg_info      = cam_ife_csid_1080_top_irq_reg_info,
	.rx_irq_reg_info       = cam_ife_csid_1080_rx_irq_reg_info,
	.path_irq_reg_info     = {
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_0],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_1],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_2],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_3],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_4],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_IPP],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_PPP],
		NULL,
		NULL,
		NULL,
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_IPP_1],
		&cam_ife_csid_1080_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_IPP_2],
	},
	.buf_done_irq_reg_info = &cam_ife_csid_1080_buf_done_irq_reg_info,
	.cmn_reg                              = &cam_ife_csid_1080_cmn_reg_info,
	.csi2_reg                             = &cam_ife_csid_1080_csi2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP]   = &cam_ife_csid_1080_ipp_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP_1] = &cam_ife_csid_1080_ipp_1_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP_2] = &cam_ife_csid_1080_ipp_2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_PPP]   = &cam_ife_csid_1080_ppp_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_0] = &cam_ife_csid_1080_rdi_0_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_1] = &cam_ife_csid_1080_rdi_1_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_2] = &cam_ife_csid_1080_rdi_2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_3] = &cam_ife_csid_1080_rdi_3_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_4] = &cam_ife_csid_1080_rdi_4_reg_info,
	.ipp_mc_reg                           = &cam_ife_csid_1080_ipp_mc_reg_info,
	.need_top_cfg = 0x0,
	.top_irq_desc        = &cam_ife_csid_1080_top_irq_desc,
	.rx_irq_desc         = &cam_ife_csid_1080_rx_irq_desc,
	.debug_vec_desc      = &cam_ife_csid_1080_debug_vec_desc,
	.path_irq_desc       = cam_ife_csid_1080_path_irq_desc,
	.num_top_err_irqs    = cam_ife_csid_1080_num_top_irq_desc,
	.num_rx_err_irqs     = cam_ife_csid_1080_num_rx_irq_desc,
	.num_path_err_irqs   = ARRAY_SIZE(cam_ife_csid_1080_path_irq_desc),
	.top_debug_mask      = &cam_ife_csid_1080_top_debug_mask,
	.rx_debug_mask       = &cam_ife_csid_1080_rx_debug_mask,
	.num_top_regs        = 2,
	.num_rx_regs         = 2,
};
#endif /*_CAM_IFE_CSID_1080_H_ */
