/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _CAM_IFE_CSID_970_H_
#define _CAM_IFE_CSID_970_H_

#include <linux/module.h>
#include "cam_ife_csid_hw_ver2.h"
#include "cam_ife_csid980.h"

#define CAM_CSID_VERSION_V970                 0x90070000

static struct cam_ife_csid_ver2_common_reg_info
			cam_ife_csid_970_cmn_reg_info = {
	.hw_version_addr                         = 0x0000,
	.cfg0_addr                               = 0x0004,
	.global_cmd_addr                         = 0x0008,
	.reset_cfg_addr                          = 0x000C,
	.reset_cmd_addr                          = 0x0010,
	.irq_cmd_addr                            = 0x0014,
	.rup_cmd_addr                            = 0x0018,
	.aup_cmd_addr                            = 0x001C,
	.rup_aup_cmd_addr                        = 0x0020,
	.offline_cmd_addr                        = 0x0024,
	.shdr_master_slave_cfg_addr              = 0x0028,
	.multi_sensor_mode_addr                  = 0x002C,
	.top_irq_status_addr                     = {0x0084, 0x0094},
	.top_irq_mask_addr                       = {0x0088, 0x0098},
	.top_irq_clear_addr                      = {0x008C, 0x009C},
	.top_irq_set_addr                        = {0x0090, 0x00A0},
	.buf_done_irq_status_addr                = 0x00A4,
	.buf_done_irq_mask_addr                  = 0x00A8,
	.buf_done_irq_clear_addr                 = 0x00AC,
	.buf_done_irq_set_addr                   = 0x00B0,
	.test_bus_ctrl                           = 0x03F4,
	.test_bus_debug                          = 0x03F8,
	.drv_cfg0_addr                           = 0x0164,
	.drv_cfg1_addr                           = 0x0168,
	.drv_cfg2_addr                           = 0x016C,
	.debug_drv_0_addr                        = 0x0170,
	.debug_drv_1_addr                        = 0x0174,
	.debug_sensor_hbi_irq_vcdt_addr          = 0x0180,
	.debug_violation_addr                    = 0x03D4,
	.debug_cfg_addr                          = 0x03E0,
	.rx_mode_id_cfg1_addr                    = 0x0470,

	/*configurations */
	.major_version                           = 6,
	.minor_version                           = 8,
	.version_incr                            = 0,
	.num_rdis                                = 4,
	.num_pix                                 = 2,
	.num_ppp                                 = 1,
	.rst_done_shift_val                      = 1,
	.path_en_shift_val                       = 31,
	.dt_id_shift_val                         = 27,
	.vc_shift_val                            = 22,
	.vc_mask                                 = 0x1F,
	.dt_shift_val                            = 16,
	.dt_mask                                 = 0x3F,
	.crop_shift_val                          = 16,
	.decode_format_shift_val                 = 12,
	.decode_format1_shift_val                = 16,
	.decode_format1_supported                = true,
	.decode_format_mask                      = 0xF,
	.frame_id_decode_en_shift_val            = 1,
	.multi_vcdt_vc1_shift_val                = 2,
	.multi_vcdt_dt1_shift_val                = 7,
	.multi_vcdt_ts_combo_en_shift_val        = 13,
	.multi_vcdt_en_shift_val                 = 0,
	.timestamp_stb_sel_shift_val             = 8,
	.vfr_en_shift_val                        = 0,
	.mup_shift_val                           = 4,
	.shdr_slave_ppp_shift                    = 16,
	.shdr_slave_rdi2_shift                   = 18,
	.shdr_slave_rdi1_shift                   = 17,
	.shdr_master_rdi0_shift                  = 4,
	.shdr_master_slave_en_shift              = 0,
	.drv_en_shift                            = 0,
	.drv_rup_en_shift                        = 0,
	.early_eof_supported                     = 1,
	.vfr_supported                           = 1,
	.multi_vcdt_supported                    = 1,
	.ts_comb_vcdt_en                         = true,
	.ts_comb_vcdt_mask                       = 3,
	.frame_id_dec_supported                  = 1,
	.measure_en_hbi_vbi_cnt_mask             = 0xc,
	.measure_pixel_line_en_mask              = 0x3,
	.crop_pix_start_mask                     = 0x3fff,
	.crop_pix_end_mask                       = 0xffff,
	.crop_line_start_mask                    = 0x3fff,
	.crop_line_end_mask                      = 0xffff,
	.drop_supported                          = 1,
	.ipp_irq_mask_all                        = 0x7FFF,
	.rdi_irq_mask_all                        = 0x7FFF,
	.ppp_irq_mask_all                        = 0xFFFF,
	.top_err_irq_mask                        = {0x00000002, 0x18},
	.rst_loc_path_only_val                   = 0x0,
	.rst_loc_complete_csid_val               = 0x1,
	.rst_mode_frame_boundary_val             = 0x0,
	.rst_mode_immediate_val                  = 0x1,
	.rst_cmd_hw_reset_complete_val           = 0x1,
	.rst_cmd_sw_reset_complete_val           = 0x2,
	.rst_cmd_irq_ctrl_only_val               = 0x4,
	.timestamp_strobe_val                    = 0x2,
	.top_reset_irq_mask                      = {0x1,},
	.rst_location_shift_val                  = 4,
	.rst_mode_shift_val                      = 0,
	.epoch_factor                            = 50,
	.global_reset                            = 1,
	.aup_rup_supported                       = 1,
	.only_master_rup                         = 1,
	.format_measure_height_mask_val          = 0xFFFF,
	.format_measure_height_shift_val         = 0x10,
	.format_measure_width_mask_val           = 0xFFFF,
	.format_measure_width_shift_val          = 0x0,
	.format_measure_max_hbi_shift            = 16,
	.format_measure_min_hbi_mask             = 0xFFF,
	.top_buf_done_irq_mask                   = 0x8,
	.decode_format_payload_only              = 0xF,
	.timestamp_enabled_in_cfg0               = true,
	.camif_irq_support                       = true,
	.capabilities                            = CAM_IFE_CSID_CAP_SPLIT_RUP_AUP |
							CAM_IFE_CSID_CAP_SKIP_PATH_CFG1 |
							CAM_IFE_CSID_CAP_SKIP_EPOCH_CFG|
							CAM_IFE_CSID_CAP_MULTI_CTXT,
	.top_top2_irq_mask                       = 0x80000000,
	.path_domain_id_cfg0                     = 0x0,
	.path_domain_id_cfg1                     = 0x4,
	.path_domain_id_cfg2                     = 0x8,
	.phy_sel_base_idx                        = 1,
};

static struct cam_ife_csid_ver2_reg_info cam_ife_csid_970_reg_info = {
	.top_irq_reg_info      = cam_ife_csid_980_top_irq_reg_info,
	.rx_irq_reg_info       = cam_ife_csid_980_rx_irq_reg_info,
	.path_irq_reg_info     = {
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_0],
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_1],
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_2],
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_3],
		NULL,
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_IPP],
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_PPP],
		NULL,
		NULL,
		NULL,
		&cam_ife_csid_980_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_IPP_1],
		NULL,
	},
	.buf_done_irq_reg_info = &cam_ife_csid_980_buf_done_irq_reg_info,
	.cmn_reg                              = &cam_ife_csid_970_cmn_reg_info,
	.csi2_reg                             = &cam_ife_csid_980_csi2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP]   = &cam_ife_csid_980_ipp_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP_1] = &cam_ife_csid_980_ipp_1_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP_2] = NULL,
	.path_reg[CAM_IFE_PIX_PATH_RES_PPP]   = &cam_ife_csid_980_ppp_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_0] = &cam_ife_csid_980_rdi_0_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_1] = &cam_ife_csid_980_rdi_1_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_2] = &cam_ife_csid_980_rdi_2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_3] = &cam_ife_csid_980_rdi_3_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_4] = NULL,
	.ipp_mc_reg                           = &cam_ife_csid_980_ipp_mc_reg_info,
	.need_top_cfg = 0x0,
	.dynamic_drv_supported = false,
	.top_irq_desc        = &cam_ife_csid_980_top_irq_desc,
	.rx_irq_desc         = &cam_ife_csid_980_rx_irq_desc,
	.path_irq_desc       = cam_ife_csid_980_path_irq_desc,
	.num_top_err_irqs    = cam_ife_csid_980_num_top_irq_desc,
	.num_rx_err_irqs     = cam_ife_csid_980_num_rx_irq_desc,
	.num_path_err_irqs   = ARRAY_SIZE(cam_ife_csid_980_path_irq_desc),
	.top_debug_mask      = &cam_ife_csid_980_top_debug_mask,
	.rx_debug_mask       = &cam_ife_csid_980_rx_debug_mask,
	.num_top_regs        = 2,
	.num_rx_regs         = 2,
};
#endif /*_CAM_IFE_CSID_970_H_ */
