#include "cam_eeprom_dev.h"
#include "cam_req_mgr_dev.h"
#include "cam_eeprom_soc.h"
#include "cam_eeprom_core.h"
#include "cam_debug_util.h"

#define OTP_OV08F10_SLAVE_ADDR      0x6C

#define OTP_OV08F10_SENSORID_REG_H   0x00
#define OTP_OV08F10_SENSORID_REG_L   0x01

struct eeprom_memory_map_init_write_params otp_ov08f10_read_byte_setting  ={
	.slave_addr = OTP_OV08F10_SLAVE_ADDR,
	.mem_settings =
        {
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0e, CAMERA_SENSOR_I2C_TYPE_BYTE,  3000},  
		{0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0b, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x10, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x08, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x11, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x5e, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x12, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x13, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x15, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x14, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x68, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x15, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x12, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x05, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x04, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x08, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x07, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x05, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x24, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xff, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x33, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x19, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xc0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x42, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x5d, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x44, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x81, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x46, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x47, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x48, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x4c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x38, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xb2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1e, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xb3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1b, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xc3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xd2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xfc, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x50, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x53, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x54, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x04, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x55, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x04, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x57, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x87, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x5e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x67, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x05, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x7a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x7c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0a, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x90, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3a, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x91, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x12, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x92, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x16, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x94, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x12, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x95, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x97, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x98, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x48, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2d, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xca, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0d, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xcb, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x12, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xcc, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x11, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xcd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x16, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xce, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0d, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xcf, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xd0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xd1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x14, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x07, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x2c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x2d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xf8, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2b, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x05, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x08, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x06, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x09, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x11, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x28, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x6f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x2a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x2b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x05, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x5e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x52, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x53, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x54, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x55, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x56, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x57, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x58, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x59, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x5c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x27, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x34, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x02, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x88, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x21, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x4b, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xd5, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xdb, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x31, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xcc, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x07, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x05, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0a, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x12, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x13, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x14, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x13, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x08, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x28, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x16, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x17, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x18, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x19, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x30, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x04, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x12, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x0a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x0b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x11, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x12, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x0d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x05, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x02, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xff, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xa1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x08, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xa2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x09, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xa3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x90, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xa5, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x08, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xa6, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xa7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xc0, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},                            
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x24, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xc0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xc1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x08, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xc2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x38, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x8e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0c, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x8f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xc0, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x90, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x09, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x91, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x90, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xb7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x1c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x19, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE,  0}, 
		{0xe7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE,  0}, 
		{0xe7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE,  3000}
	},
	.memory_map_size = 142,
};


struct eeprom_memory_map_init_write_params otp_ov08f10_set_page_setting  ={
	.slave_addr = OTP_OV08F10_SLAVE_ADDR,
	.mem_settings =
        {
		{0xfd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9F, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0x9D, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xA9, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xFF, CAMERA_SENSOR_I2C_TYPE_BYTE,  0},
		{0xFD, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x09, CAMERA_SENSOR_I2C_TYPE_BYTE,  0}
	},
	.memory_map_size = 5,
};



void init_otp_read_byte_ov08f10(struct cam_eeprom_ctrl_t *e_ctrl){

	struct eeprom_memory_map_init_write_params *pWriteParams = NULL;
	struct cam_sensor_i2c_reg_array    i2c_reg_array = {0};
	struct cam_sensor_i2c_reg_setting  i2c_reg_settings = {0};
	uint32_t count_write;
	int rc = 0;
	pWriteParams = &otp_ov08f10_read_byte_setting;
	for(count_write=0;count_write < pWriteParams->memory_map_size; count_write++) {
		i2c_reg_settings.addr_type = pWriteParams->mem_settings[count_write].addr_type;
		i2c_reg_settings.data_type = pWriteParams->mem_settings[count_write].data_type;
		i2c_reg_settings.size = 1;
		i2c_reg_array.reg_addr = pWriteParams->mem_settings[count_write].reg_addr;
		i2c_reg_array.reg_data = pWriteParams->mem_settings[count_write].reg_data;
		i2c_reg_array.delay = pWriteParams->mem_settings[count_write].delay;
		i2c_reg_settings.reg_setting = &i2c_reg_array;

		CAM_DBG(CAM_EEPROM, "count_write %d,%d %d", count_write,i2c_reg_settings.addr_type,i2c_reg_settings.data_type);
		CAM_DBG(CAM_EEPROM, "20250329 count_write %d,0x%x 0x%x", count_write,i2c_reg_array.reg_addr,i2c_reg_array.reg_data);
		
		rc = camera_io_dev_write(&(e_ctrl->io_master_info), &i2c_reg_settings);
		if (rc) {
			CAM_ERR(CAM_EEPROM, "20250329 write init params failed rc %d", rc);
			return ;
		}
	}
	return ;
}

void otp_set_page_ov08f10(struct cam_eeprom_ctrl_t *e_ctrl, int page){

	struct eeprom_memory_map_init_write_params *pWriteParams = NULL;
	struct cam_sensor_i2c_reg_array    i2c_reg_array = {0};
	struct cam_sensor_i2c_reg_setting  i2c_reg_settings = {0};
	uint32_t count_write;
	int rc = 0;
	pWriteParams = &otp_ov08f10_set_page_setting;
	for(count_write=0;count_write < pWriteParams->memory_map_size; count_write++) {
		i2c_reg_settings.addr_type = pWriteParams->mem_settings[count_write].addr_type;
		i2c_reg_settings.data_type = pWriteParams->mem_settings[count_write].data_type;
		i2c_reg_settings.size = 1;
		i2c_reg_array.reg_addr = pWriteParams->mem_settings[count_write].reg_addr;
		i2c_reg_array.reg_data = pWriteParams->mem_settings[count_write].reg_data;
		if(count_write == 3)
			i2c_reg_array.reg_data = page;
		i2c_reg_array.delay = pWriteParams->mem_settings[count_write].delay;
		i2c_reg_settings.reg_setting = &i2c_reg_array;

		CAM_DBG(CAM_EEPROM, "count_write %d,%d %d", count_write,i2c_reg_settings.addr_type,i2c_reg_settings.data_type);
		CAM_DBG(CAM_EEPROM, "20250329 count_write %d,0x%x 0x%x", count_write,i2c_reg_array.reg_addr,i2c_reg_array.reg_data);
		rc = camera_io_dev_write(&(e_ctrl->io_master_info), &i2c_reg_settings);
		if (rc) {
			CAM_ERR(CAM_EEPROM, "20250329 write init params failed rc %d", rc);
			return ;
		}
	}
	return ;
}
