#ifndef _QVGA_SP08821_II_H_
#define _QVGA_SP08821_II_H_

#include "cam_eeprom_dev.h"
#include "cam_req_mgr_dev.h"
#include "cam_eeprom_soc.h"
#include "cam_eeprom_core.h"
#include "cam_debug_util.h"
#include "camera_main.h"

#define QVGA_SP0821_SLAVE_ADDR      0x86
#define QVGA_SP0821_SLAVE_ADDR_REG  0x02
#define QVGA_SP0821_LUX_DATA_REG    0xb0

struct eeprom_memory_map_init_write_params qvga_sp0821_setting  ={
	.slave_addr = QVGA_SP0821_SLAVE_ADDR,
	.mem_settings =
	{
		{0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x04, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x96, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x24, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x13, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x9b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xd7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc5, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xc7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc6, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xe2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xe7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xbf, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xba, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x5a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xbb, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x69, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xe7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x07, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x31, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x2c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x2e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x28, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x29, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x14, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xb0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x38, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x50, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x39, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x52, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x3a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x60, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x3b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x3c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xe0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x85, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xe0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xe5, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x60, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xf5, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x02, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xf1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x03, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xf3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x41, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x05, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x06, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x07, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x08, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x09, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x0a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x34, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x0D, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc8, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x29, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa4, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa5, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa8, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x32, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa9, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xaa, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x01, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xab, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x4c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x80, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x4d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x80, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa6, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xac, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xad, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x8a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x8b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x8c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x8d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x26, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x8e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x26, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x8f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x24, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x90, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x24, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x91, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x22, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x92, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x22, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x93, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x22, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x94, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x95, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x96, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x17, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x88, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x18, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x80, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x4e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x4f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x58, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x8a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x59, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xa8, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x5a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x80, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xca, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x86, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x08, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x87, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x88, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x30, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x89, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x45, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x9e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x94, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x9f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x88, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x97, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x84, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x98, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x88, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x99, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x74, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x9a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x84, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x7c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xa1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x78, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x9d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x09, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xB1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x04, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xb3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x47, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xb8, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x04, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xb9, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x28, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x3f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x18, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc1, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xff, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc3, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xff, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc4, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x40, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc5, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xc7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc6, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xe2, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xef, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc8, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x50, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x51, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x52, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x53, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xcf, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x54, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xd0, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x5c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x5d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x21, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x5e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x5f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xe9, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x60, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x98, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xcb, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xcc, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xcd, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x3f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xce, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x85, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xcf, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xff, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x79, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x5a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x7a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xDC, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x7b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0A, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x7c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xFD, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x7d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x46, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x7e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xFD, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x7f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xFD, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x80, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xEF, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x81, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x54, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x1b, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x1c, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x0f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x1d, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x15, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x1e, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x15, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x15, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x21, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x22, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x2a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x56, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x49, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x1a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x14, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x34, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x82, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x10, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x83, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x00, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0x84, CAMERA_SENSOR_I2C_TYPE_BYTE, 0xff, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xd7, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x50, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xd8, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1a, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xd9, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x20, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xc9, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x1f, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xbf, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x33, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xba, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x37, CAMERA_SENSOR_I2C_TYPE_BYTE, 0},
		{0xbb, CAMERA_SENSOR_I2C_TYPE_BYTE, 0x38, CAMERA_SENSOR_I2C_TYPE_BYTE, 5},
	},
	.memory_map_size = 154,
};

static int get_qvga_lux_data_sp0821(struct cam_eeprom_ctrl_t *e_ctrl){
	uint32_t lux = 0;

	camera_io_dev_read( &(e_ctrl->io_master_info),
				QVGA_SP0821_LUX_DATA_REG, &lux, CAMERA_SENSOR_I2C_TYPE_BYTE,
				CAMERA_SENSOR_I2C_TYPE_BYTE);
	CAM_INFO(CAM_EEPROM, "lux: 0x%x", lux);
	return lux;
}

static void init_qvga_setting_sp0821(struct cam_eeprom_ctrl_t *e_ctrl){

	struct eeprom_memory_map_init_write_params *pWriteParams = NULL;
	struct cam_sensor_i2c_reg_array    i2c_reg_array = {0};
	struct cam_sensor_i2c_reg_setting  i2c_reg_settings = {0};
	uint32_t count_write;
	int rc = 0;
	pWriteParams = &qvga_sp0821_setting;
	for(count_write=0;count_write < pWriteParams->memory_map_size; count_write++) {
		i2c_reg_settings.addr_type = pWriteParams->mem_settings[count_write].addr_type;
		i2c_reg_settings.data_type = pWriteParams->mem_settings[count_write].data_type;
		i2c_reg_settings.size = 1;
		i2c_reg_array.reg_addr = pWriteParams->mem_settings[count_write].reg_addr;
		i2c_reg_array.reg_data = pWriteParams->mem_settings[count_write].reg_data;
		i2c_reg_array.delay = pWriteParams->mem_settings[count_write].delay;
		i2c_reg_settings.reg_setting = &i2c_reg_array;

		CAM_DBG(CAM_EEPROM, "count_write %d,%d %d", count_write,i2c_reg_settings.addr_type,i2c_reg_settings.data_type);
		CAM_DBG(CAM_EEPROM, "count_write %d,0x%x 0x%x", count_write,i2c_reg_array.reg_addr,i2c_reg_array.reg_data);
		rc = camera_io_dev_write(&(e_ctrl->io_master_info), &i2c_reg_settings);
		if (rc) {
			CAM_ERR(CAM_EEPROM, "write init params failed rc %d", rc);
			return ;
		}
	}
	return ;
}

static ssize_t qvga_get_name_sp0821(int driver_flag, char *buf)
{
	ssize_t len = 0;
	if (driver_flag) {
		len += snprintf(buf + len, PAGE_SIZE - len, "%s\n",
				"sp0821_iii");
	} else {
		len += snprintf(buf + len, PAGE_SIZE - len, "%s\n",
				"none");
	}
	return len;
}
#endif